### ISSUE TITLE
Menu disappears in LibraryActivity

### ISSUE THREAD

**Issue by anlalalu** [vanilla-music/vanilla#1001]
- Vanilla Music Version (Settings -> About): 1.0.84
- Android Version: 4.4.4
- Phone vendor / model: Android emulator
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [ ] F-Droid
  - [ x ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [ x ] NA / Don't know.

## Description
The menu disappears after rotation with error log. Vanilla also directly turns back to home interface after the rotation which is not expected.
....

## Steps to reproduce the issue

1. tap 'more options'
2. tap 'show queue'
3. tap 'more options'
4. rotate the screen

## Screenshot / Video (If applicable)
![image](https://user-images.githubusercontent.com/46981872/71256269-2c4df200-236b-11ea-9d55-704311f1a8de.png)

**Comment by anlalalu** [comment]
Do you consider this as a defect?

**Comment by adrian-bl** [comment]
Yes, but i can not reproduce it on my phone (and currently have very little time to work on vanilla).

Could you post the stacktrace of the crash?

**Comment by anlalalu** [comment]
The stacktrace is:

E/WindowManager: android.view.WindowLeaked: Activity ch.blinkenlights.android.vanilla.LibraryActivity has leaked window android.widget.PopupWindow$PopupViewContainer{529a91f0 V.E..... ........ 0,0-424,716} that was originally added here
                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                    at android.widget.PopupWindow.invokePopup(PopupWindow.java:1019)
                                                    at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:925)
                                                    at android.widget.ListPopupWindow.show(ListPopupWindow.java:625)
                                                    at com.android.internal.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:148)
                                                    at com.android.internal.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:113)
                                                    at android.widget.PopupMenu.show(PopupMenu.java:167)
                                                    at ch.blinkenlights.android.vanilla.BottomBarControls.openMenu(BottomBarControls.java:202)
                                                    at ch.blinkenlights.android.vanilla.BottomBarControls.onClick(BottomBarControls.java:110)
                                                    at android.view.View.performClick(View.java:4438)
                                                    at android.view.View$PerformClick.run(View.java:18422)
                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:136)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by adrian-bl** [comment]
Hmmm... That doesnt look like a crash: anything else you see in the logs?

**Comment by anlalalu** [comment]
Yes, the app will not crash, but the menu disappears and the app returns to home interface which is not expected. May be judged as a minor issue which can be repaired later.
