### ISSUE TITLE
setNextMediaPlayer failed and crash when playing APE format music on Android 9

### ISSUE THREAD

**Issue by zollty** [vanilla-music/vanilla#1005]
- Vanilla Music Version (Settings -> About): 1.0.84 and previous
- Android Version: 9
- Phone vendor / model: OPPO ColorOS v6.1
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [ ] F-Droid
  - [ x ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ x ] No
  - [ ] NA / Don't know.

## Description

....

## Steps to reproduce the issue
1、

Open Vanilla

Play a song with APE format

Crash and Exit

2、
Open Vanilla

Play a song with other formats

Next to a song with APE format

Auto Stop and back to the list

3、
Open Vanilla

Play a song with other formats

Prev to a song with APE format

It's OK

4、
Open a file browser, and select a  song with APE format

Play it with vanilla music

It's OK

## Logs

```text
01-09 15:38:45.088   866   918 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
01-09 15:38:45.302  1158  1405 E OmaDrmFile: Unable to open Temp media file : No such file or directory
01-09 15:38:45.302  1158  1405 E OmaDrmFile: Invalid drm version
01-09 15:38:45.309  1173 27599 E MM_OSAL : FileSource::FileSource
01-09 15:38:45.309  1173 27599 E MM_OSAL : FileSource::FileSource m_bEveryThingOK 1
01-09 15:38:45.309  1173 27599 E MM_OSAL : MM_File_Create failed .Efs Error No -1 , File Name /data/mmosal_logmask.cfg , Mode 0
01-09 15:38:45.309  1173 27599 E MM_OSAL : Open or read fail on /data/mmosal_logmask.cfg. Possible permission denied issue. Looking for /data/misc/media/mmosal_logmask.cfg
01-09 15:38:45.309  1173 27599 E MM_OSAL : MM_File_Create failed .Efs Error No -1 , File Name /data/misc/media/mmosal_logmask.cfg , Mode 0
01-09 15:38:45.310  1173 27599 E MMParserExtractor: APE getFormatBlock size = 32
01-09 15:38:45.314  1178 18208 W BpMediaSource: ignoring potentially modified MetaData from start
01-09 15:38:45.314  1178 18208 W BpMediaSource: input:
01-09 15:38:45.314  1178 18208 W BpMediaSource: output:
01-09 15:38:45.324  1178 18207 W GenericSource: Is ape file, use oppo media monkey audio decode, return.
01-09 15:38:45.324  1178 18207 W Utils   : track of type 'audio/x-ape' does not publish channel mask, channel count 2
01-09 15:38:45.330  1178 18207 W Utils   : track of type 'audio/x-ape' does not publish channel mask, channel count 2
01-09 15:38:45.332 18162 18174 E MediaPlayerNative: error (1, 0)
01-09 15:38:45.340 18162 18162 E MediaPlayer: Error (1,0)
01-09 15:38:45.342  1204  1204 W media.codec: Failed to obtain quirks for omx component 'OMX.qti.audio.decoder.ape.sw' from XML files
01-09 15:38:45.343  1518  4078 E NotificationService: Suppressing notification from package by user request.
01-09 15:38:45.344  1204  1204 E OMXNodeInstance: setConfig(0xe68e9004:qti.decoder.ape.sw, ConfigPriority(0x6f800002)) ERROR: UnsupportedIndex(0x8000101a)
01-09 15:38:45.345  1204  1204 E OMXNodeInstance: setConfig(0xe68e9004:qti.decoder.ape.sw, ConfigPriority(0x6f800002)) ERROR: UnsupportedIndex(0x8000101a)
01-09 15:38:45.346  1204  1204 E OMXNodeInstance: getConfig(0xe68e9004:qti.decoder.ape.sw, ConfigAndroidVendorExtension(0x6f100004)) ERROR: UnsupportedIndex(0x8000101a)
01-09 15:38:45.346  1178 18212 W ExtendedACodec: Failed to get extension for extradata parameter
01-09 15:38:45.349   824   824 W AshmemAllocator: ashmem_create_region(212345) returning hidl_memory(0x7a7002c100, 212345)
01-09 15:38:45.350   824   824 W AshmemAllocator: ashmem_create_region(212345) returning hidl_memory(0x7a7002c100, 212345)
01-09 15:38:45.352   824   824 W AshmemAllocator: ashmem_create_region(2097152) returning hidl_memory(0x7a7002c100, 2097152)
01-09 15:38:45.353   824   824 W AshmemAllocator: ashmem_create_region(2097152) returning hidl_memory(0x7a7002c100, 2097152)
01-09 15:38:45.356  1178 18211 W MediaAnalyticsItem: Unable to record: [1:codec:0:-1::0:-1:1:0:5:android.media.mediacodec.codec=OMX.qti.audio.decoder.ape.sw:android.media.mediacodec.mode=audio:android.media.mediacodec.secure=0:android.media.mediacodec.encoder=0:android.media.mediacodec.mime=audio/x-ape:] [forcenew=0]
01-09 15:38:45.359  1173 27599 W MediaAnalyticsItem: Unable to record: [1:extractor:0:-1::0:-1:1:0:3:android.media.mediaextractor.fmt=MMParserExtractor:android.media.mediaextractor.ntrk=1:android.media.mediaextractor.mime=audio/x-ape:] [forcenew=0]
01-09 15:38:45.360  1518  1518 W AudioService: couldn't find receiver package for effect intent
01-09 15:38:45.360 18162 18184 E MediaPlayerNative: start called in state 1, mPlayer(0x0)
01-09 15:38:45.360 18162 18184 E MediaPlayerNative: error (-38, 0)
01-09 15:38:45.367 18162 18162 W HardwarePlatform: mIsQcom 1 mIsMtk 0
01-09 15:38:45.367 18162 18162 W OppoAwesomePlayer: reset in
01-09 15:38:45.367 18162 18162 W OppoAwesomePlayer: reset_l in
01-09 15:38:45.367 18162 18162 W OppoAwesomePlayer: notifyListener_l mSeeking 0
01-09 15:38:45.368 18162 18162 W OppoAwesomePlayer: reset_l out
01-09 15:38:45.368 18162 18162 W OppoAwesomePlayer: reset out
01-09 15:38:45.368 18162 18162 W OppoAwesomePlayer: AwesomePlayer
01-09 15:38:45.368 18162 18162 W OppoAwesomePlayer: setDataSource fd /storage/emulated/0/02-LOCAL/my-music/she.ape
01-09 15:38:45.368 18162 18162 W OppoAwesomePlayer: reset_l in
01-09 15:38:45.368 18162 18162 W OppoAwesomePlayer: notifyListener_l mSeeking 0
01-09 15:38:45.368 18162 18162 W OppoAwesomePlayer: reset_l out
01-09 15:38:45.368 18162 18162 W FfmpegSource: begin SniffFfmpeg
01-09 15:38:45.368 18162 18162 W APEExtractor: filename /storage/emulated/0/02-LOCAL/my-music/she.ape
01-09 15:38:45.371 18162 18162 E MediaPlayer: handleMediaPlayerError() mOppoMediaPlayer prepare mPrepareAsync=false
01-09 15:38:45.371 18162 18162 W OppoAwesomePlayer: prepare begin
01-09 15:38:45.371 18162 18162 W OppoAwesomePlayer: prepareAsync_l begin
01-09 15:38:45.371 18162 18162 W OppoAwesomePlayer: prepareAsync_l in
01-09 15:38:45.371 18162 18162 W OppoAwesomePlayer: prepareAsync_l out
01-09 15:38:45.371 18162 18162 W OppoAwesomePlayer: prepareAsync_l end
01-09 15:38:45.377 18162 18162 W OppoAwesomePlayer: prepare_l end
01-09 15:38:45.377 18162 18162 W OppoAwesomePlayer: begin play
01-09 15:38:45.377 18162 18162 W OppoAwesomePlayer: begin play_l
01-09 15:38:45.387 18162 18162 W AudioOutput: open(44100, 2, 0x0, 1, 4, 5353)
01-09 15:38:45.389 18162 18162 W AudioOutput:  buffersize = 14144
01-09 15:38:45.389 18162 18184 W AudioManager: Use of stream types is deprecated for operations other than volume control
01-09 15:38:45.389 18162 18184 W AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
01-09 15:38:45.389  1518  1636 E NotificationService: Suppressing notification from package by user request.
01-09 15:38:45.391   905  4756 E MMListParser: getProcessNameByPid bad param
01-09 15:38:45.394 18162 18162 W AudioTrack: Use of stream types is deprecated for operations other than volume control
01-09 15:38:45.394 18162 18162 W AudioTrack: See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
01-09 15:38:45.399 18162 18162 E MediaPlayer: Error (-38,0)
01-09 15:38:45.399 18162 18162 E MediaPlayer: OppoMediaPlayer has been created, ignore this MediaPlayer MEDIA_ERROR
01-09 15:38:45.400   866   918 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
01-09 15:38:45.401   823 15338 E msm8974_platform: platform_check_backends_match: Invalid snd_device =
01-09 15:38:45.401   823 15338 E voice   : voice_is_in_call_rec_stream: input stream is NULL
01-09 15:38:45.401   823 15338 E audio_hw_utils: send_app_type_cfg_for_device: Could not get ctl for mixer cmd - Audio Stream Capture 35 App Type Cfg
01-09 15:38:45.402   823 15338 E ACDB-LOADER: Error: ACDB_CMD_GET_AUDPROC_INSTANCE_GAIN_DEP_STEP_TABLE_SIZE Returned = -19
01-09 15:38:45.402   823 15338 E ACDB-LOADER: Error: ACDB AudProc vol returned = -19
01-09 15:38:45.417   823 15338 E audio_hw_spkr_dsm: audio_extn_spkr_dsm_start_processing: Exit
01-09 15:38:45.418   823 15338 E         : __gcs_disable_update_pld: sgt_array[i] = 0x1
01-09 15:38:45.418   823 15338 E         : __gcs_disable_update_pld: sgt_array[i] = 0x2
01-09 15:38:45.424  1158  1405 E OmaDrmFile: Unable to open Temp media file : No such file or directory
01-09 15:38:45.424  1158  1405 E OmaDrmFile: Invalid drm version
01-09 15:38:45.433  1173  1173 E MM_OSAL : FileSource::FileSource
01-09 15:38:45.433  1173  1173 E MM_OSAL : FileSource::FileSource m_bEveryThingOK 1
01-09 15:38:45.433  1173  1173 E MM_OSAL : MM_File_Create failed .Efs Error No -1 , File Name /data/mmosal_logmask.cfg , Mode 0
01-09 15:38:45.433  1173  1173 E MM_OSAL : Open or read fail on /data/mmosal_logmask.cfg. Possible permission denied issue. Looking for /data/misc/media/mmosal_logmask.cfg
01-09 15:38:45.433  1173  1173 E MM_OSAL : MM_File_Create failed .Efs Error No -1 , File Name /data/misc/media/mmosal_logmask.cfg , Mode 0
01-09 15:38:45.434  1173  1173 E MMParserExtractor:  get metadata failed for meta type 19, size 0
01-09 15:38:45.439  1178 18224 W BpMediaSource: ignoring potentially modified MetaData from start
01-09 15:38:45.439  1178 18224 W BpMediaSource: input:
01-09 15:38:45.439  1178 18224 W BpMediaSource: output:
01-09 15:38:45.443 18162 18184 E AndroidRuntime: FATAL EXCEPTION: PlaybackService
01-09 15:38:45.443 18162 18184 E AndroidRuntime: Process: ch.blinkenlights.android.vanillanightly, PID: 18162
01-09 15:38:45.443 18162 18184 E AndroidRuntime: java.lang.IllegalArgumentException: setNextMediaPlayer failed.: status=0xFFFFFFED
01-09 15:38:45.443 18162 18184 E AndroidRuntime:        at android.media.MediaPlayer.setNextMediaPlayer(Native Method)
01-09 15:38:45.443 18162 18184 E AndroidRuntime:        at ch.blinkenlights.android.vanillanightly.VanillaMediaPlayer.setNextMediaPlayer(VanillaMediaPlayer.java:91)
01-09 15:38:45.443 18162 18184 E AndroidRuntime:        at ch.blinkenlights.android.vanillanightly.PlaybackService.triggerGaplessUpdate(PlaybackService.java:830)
01-09 15:38:45.443 18162 18184 E AndroidRuntime:        at ch.blinkenlights.android.vanillanightly.PlaybackService.handleMessage(PlaybackService.java:1640)
01-09 15:38:45.443 18162 18184 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
01-09 15:38:45.443 18162 18184 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:216)
01-09 15:38:45.443 18162 18184 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:65)
01-09 15:38:45.448   823 15338 E ACDB-LOADER: Error: ACDB_CMD_GET_AFE_INSTANCE_COMMON_TABLE_SIZE Returned = -19
01-09 15:38:45.448   823 15338 E ACDB-LOADER: Error: ACDB AFE returned = -19
01-09 15:38:45.451   823 15338 E audio_route: unable to find path 'listen-voice-wakeup-1 preproc port'
01-09 15:38:45.452  1518  3198 W ActivityManager:   Force finishing activity ch.blinkenlights.android.vanillanightly/.LibraryActivity
01-09 15:38:45.455  1518  3198 E ScreenModeManager: updateGlobalModeId modeId 1 mCurrentModeId 1
01-09 15:38:45.470  1518  3215 E ScreenModeManager: updateGlobalModeId modeId 1 mCurrentModeId 1
01-09 15:38:45.477  1518  4078 E ScreenModeManager: updateGlobalModeId modeId 1 mCurrentModeId 1
01-09 15:38:45.480  1518  3011 E Process : get_ion_cache_memory: Unable to open /d/ion/heaps/system
01-09 15:38:45.484  1518  2832 E ScreenModeManager: updateGlobalModeId modeId 1 mCurrentModeId 1
01-09 15:38:45.484 28811 28811 W DCS-DcsWorker: abandon unknown msgType.
01-09 15:38:45.484 28811 28811 W System.err: java.lang.Exception: Stack trace
01-09 15:38:45.485 28811 28811 W System.err:    at java.lang.Thread.dumpStack(Thread.java:1348)
01-09 15:38:45.485 28811 28811 W System.err:    at com.nearme.statistics.rom.b.d.a(DcsWorker.java:61)
01-09 15:38:45.485 28811 28811 W System.err:    at com.nearme.statistics.rom.receiver.Receiver.onReceive(Receiver.java:59)
01-09 15:38:45.485 28811 28811 W System.err:    at android.app.ActivityThread.handleReceiver(ActivityThread.java:3701)
01-09 15:38:45.485 28811 28811 W System.err:    at android.app.ActivityThread.access$1500(ActivityThread.java:225)
01-09 15:38:45.485 28811 28811 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1873)
01-09 15:38:45.485 28811 28811 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
01-09 15:38:45.485 28811 28811 W System.err:    at android.os.Looper.loop(Looper.java:216)
01-09 15:38:45.485 28811 28811 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:7300)
01-09 15:38:45.485 28811 28811 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
01-09 15:38:45.485 28811 28811 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
01-09 15:38:45.485 28811 28811 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
01-09 15:38:45.492  1518  4053 E ScreenModeManager: updateGlobalModeId modeId 1 mCurrentModeId 1
01-09 15:38:45.503  1518  2129 E ScreenModeManager: updateGlobalModeId modeId 1 mCurrentModeId 1
01-09 15:38:45.505   910  2953 W DispPerfService: onFrameAvailable: sequence=4794 com.oppo.launcher/com.oppo.launcher.Launcher#0 (2783,-1)
01-09 15:38:45.505   823 15338 E ACDB-LOADER: Error: ACDB_CMD_GET_AUDPROC_INSTANCE_GAIN_DEP_STEP_TABLE_SIZE Returned = -19
01-09 15:38:45.505   823 15338 E ACDB-LOADER: Error: ACDB AudProc vol returned = -19
01-09 15:38:45.507  1518  2129 E ScreenModeManager: updateGlobalModeId modeId 1 mCurrentModeId 1
01-09 15:38:45.518  1518  2129 E ScreenModeManager: updateGlobalModeId modeId 1 mCurrentModeId 1
01-09 15:38:45.519  1518  2628 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 18162 uid 10176
01-09 15:38:45.526  1518  2129 E ScreenModeManager: updateGlobalModeId modeId 1 mCurrentModeId 1
01-09 15:38:45.530  1518  1636 E ScreenModeManager: updateGlobalModeId modeId 1 mCurrentModeId 1
01-09 15:38:45.535  1518  1636 E ScreenModeManager: updateGlobalModeId modeId 1 mCurrentModeId 1
01-09 15:38:45.536  1178 18223 W AMessage: failed to post message as target looper for handler 0 is gone.
01-09 15:38:45.536   910  1012 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{e253a52 token=Token{ef2eedd ActivityRecord{749c2b4 u0 ch.blinkenlights.android.vanillanightly/.LibraryActivity t49}}}#0
01-09 15:38:45.539  1173  1173 W MediaAnalyticsItem: Unable to record: [1:extractor:0:-1::0:-1:1:0:3:android.media.mediaextractor.fmt=MMParserExtractor:android.media.mediaextractor.ntrk=1:android.media.mediaextractor.mime=audio/mpeg:] [forcenew=0]
01-09 15:38:45.541  1518  2129 E ScreenModeManager: updateGlobalModeId modeId 1 mCurrentModeId 1
01-09 15:38:45.543  1518  1643 W libprocessgroup: kill(-18162, 9) failed: No such process
01-09 15:38:45.544   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:45.544   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:45.545  1518  3309 W ActivityManager: app.persistent false app.isolated false app.removed false app ProcessRecord{a4e7913 18162:ch.blinkenlights.android.vanillanightly/u0a176}
01-09 15:38:45.546  1518  3309 E ScreenModeManager: updateGlobalModeId modeId 1 mCurrentModeId 1
01-09 15:38:45.549  1518  1656 W ActivityManager: setHasOverlayUi called on unknown pid: 18162
01-09 15:38:45.549 29693 29693 E PhoneState: iconId is 0android.widget.ImageView{c36923f G.ED..... ......I. 0,0-0,0 #7f0a0117 app:id/data_inout}
01-09 15:38:45.559  3257  5540 E OppoGuardElf: AbnormalAppMonitor_service: App Upgrade: F ch.blinkenlights.android.vanillanightly
01-09 15:38:45.563 29742 29751 W System  : A resource failed to call close.
01-09 15:38:45.565 29742 29751 W System  : A resource failed to call close.
01-09 15:38:45.588  4120  4120 E NfcApduServiceInfo: SE extension not present, Setting default offhost seID
01-09 15:38:45.596   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:45.598   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:45.613   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:45.614   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:46.172  1518  2129 E ScreenModeManager: updateGlobalModeId modeId 1 mCurrentModeId 1
01-09 15:38:46.949  1518  1638 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
01-09 15:38:46.957  1518  1638 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
01-09 15:38:46.972   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:46.990   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:46.999   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:47.009   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:47.013   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:47.022   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:47.027   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:47.031   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:47.036   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:47.038   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:47.042  3566  8165 E Parcel  : Reading a NULL string not supported here.
01-09 15:38:47.042  3566  5609 E Parcel  : Reading a NULL string not supported here.
01-09 15:38:47.044  3566  8165 E Parcel  : Reading a NULL string not supported here.
01-09 15:38:47.044  3566  5609 E Parcel  : Reading a NULL string not supported here.
01-09 15:38:47.045  3566  5609 E Parcel  : Reading a NULL string not supported here.
01-09 15:38:47.046  3566  8165 E Parcel  : Reading a NULL string not supported here.
01-09 15:38:47.048  3566  8165 E Parcel  : Reading a NULL string not supported here.
01-09 15:38:47.049  3566  8165 E Parcel  : Reading a NULL string not supported here.
01-09 15:38:47.049   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:47.053  3566  5459 E Parcel  : Reading a NULL string not supported here.
01-09 15:38:47.058   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:47.417  1518  1518 W NotificationService: Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@e42da1f in package ch.blinkenlights.android.vanillanightly
01-09 15:38:48.547  1518  2413 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
01-09 15:38:48.556   823   823 E audio_hw_spkr_dsm: audio_extn_spkr_dsm_stop_processing: Entry
01-09 15:38:48.567   823   823 E audio_hw_spkr_dsm: audio_extn_spkr_dsm_stop_processing: Exit
01-09 15:38:49.480  1518  1529 W JHwRemoteBinder: BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.android.server.engineer.OppoEngineerNative$HidlDeathRecipient
01-09 15:38:49.505  1518  1530 E SurfaceComposerClient: SurfaceComposerClient::destroySurface mStatus != NO_ERROR!
01-09 15:38:50.515 19826 19870 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
01-09 15:38:52.068   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:52.074   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:52.083   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:52.091   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:52.097   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:52.100   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:52.412  1182  1342 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
01-09 15:38:53.381  1518  3309 E Process : get_ion_cache_memory: Unable to open /d/ion/heaps/system
01-09 15:38:53.599   823  1623 W sound_trigger_hw: ape_enable_port_control: Invalid sound trigger port control
01-09 15:38:53.956   823  1623 E         : gcs_get_sg_mod_conn_and_update_pld: subgraph mod conn size 0. Exiting
01-09 15:38:53.956   823  1623 E         : __gcs_get_sg_conn_and_update_pld: subgraph conn size 0. Exiting
01-09 15:38:54.025   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:54.062   553   553 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
01-09 15:38:58.423  1518  1518 W WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@67973ae
^C
```

**Comment by adrian-bl** [comment]
We crash here:
```
01-09 15:38:45.443 18162 18184 E AndroidRuntime: Process: ch.blinkenlights.android.vanillanightly, PID: 18162
01-09 15:38:45.443 18162 18184 E AndroidRuntime: java.lang.IllegalArgumentException: setNextMediaPlayer failed.: status=0xFFFFFFED
01-09 15:38:45.443 18162 18184 E AndroidRuntime:        at android.media.MediaPlayer.setNextMediaPlayer(Native Method)
01-09 15:38:45.443 18162 18184 E AndroidRuntime:        at ch.blinkenlights.android.vanillanightly.VanillaMediaPlayer.setNextMediaPlayer(VanillaMediaPlayer.java:91)
01-09 15:38:45.443 18162 18184 E AndroidRuntime:        at ch.blinkenlights.android.vanillanightly.PlaybackService.triggerGaplessUpdate(PlaybackService.java:830)
01-09 15:38:45.443 18162 18184 E AndroidRuntime:        at ch.blinkenlights.android.vanillanightly.PlaybackService.handleMessage(PlaybackService.java:1640)
01-09 15:38:45.443 18162 18184 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
01-09 15:38:45.443 18162 18184 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:216)
01-09 15:38:45.443 18162 18184 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:65)
```

overall, that looks like a bug in your ROM.

I commited 690bb889abcd0462dd63b2a89178974872b0efe3 to also catch the `IllegalArgumentException` - but i'm not sure how well we will be able to recover (vanilla will likely just crash later as the media framework will be in a bad state)

**Comment by zollty** [comment]
Yeah, I debugged the program. At first, I thought it was a ROM bug, but when I choose a APE file and play it with vanilla, it's normal!    

Then I tested several other music players and they all played normally, e.g. [Odyssey Music Player](https://github.com/gateship-one/odyssey)     

I did my best to check the problem. I found out when the code reaches `VanillaMediaPlayer.setNextMediaPlayer:91`, the argument(music object) becomes null, but it exists in the previous method!    

 So I doubt it is a multi-thread problem, but I couldn't find out where the value had changed. Forgive me, I'm not a professional Andorid developer.
