### ISSUE TITLE
 Rotating when filling in the playlist name will cause a crash

### ISSUE THREAD

**Issue by sjl872964789** [vanilla-music/vanilla#1048]
- Vanilla Music Version (Settings -> About): 1.0.85
- Android Version: Android 7.1.2
- Phone vendor / model: Galaxy A6s 
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x ] NA / Don't know.

## Description

 Rotating when filling in the playlist name will cause a crash

## Steps to reproduce the issue

1. Install and open vanilla
2. Rotate the device to landscape
3. Click the three dots in the upper right corner
4. Click on "Save as playlist..."
5. Click on "New playlist"
6. Rotate the device
7.Crash

## Screenshot / Video (If applicable)
![ezgif com-video-to-gif (13)](https://user-images.githubusercontent.com/15941953/90955879-f641ae80-e4b3-11ea-8d9a-a082711200ac.gif)

## Logcat
```
08-22 20:04:25.480  9207  9207 E AndroidRuntime: FATAL EXCEPTION: main
08-22 20:04:25.480  9207  9207 E AndroidRuntime: Process: ch.blinkenlights.android.vanilla, PID: 9207
08-22 20:04:25.480  9207  9207 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x0
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2961)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3039)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4898)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.ActivityThread.-wrap18(Unknown Source:0)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6746)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
08-22 20:04:25.480  9207  9207 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.content.res.Resources.getText(Resources.java:339)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.content.Context.getText(Context.java:543)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.AlertDialog$Builder.setPositiveButton(AlertDialog.java:612)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at ch.blinkenlights.android.vanilla.PlaylistInputDialog.onCreateDialog(PlaylistInputDialog.java:96)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:406)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.Fragment.performGetLayoutInflater(Fragment.java:1325)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3027)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2979)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7030)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7015)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2914)
08-22 20:04:25.480  9207  9207 E AndroidRuntime:        ... 10 more
```

**Comment by sjl872964789** [comment]
Hi，any update about this issue？It would be really appreciated to get your concern on this.
