### ISSUE TITLE
Android 11: Crash on startup - MediaScannerThread NullPointerException

### ISSUE THREAD

**Issue by gsantner** [vanilla-music/vanilla#1064]
- Vanilla Music Version (Settings -> About): 1.0.85
- Android Version: 11
- Phone vendor / model: Poco
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know. - new phone, first install.

## Description
Crash on startup. Installed from F-Droid, all permissions / (file permission) granted via system settings.

Crashes on first start, as well further starts - not a single activity has been shown up among multiple app starts.

![Screenshot_20201115-135744_Trebuchet](https://user-images.githubusercontent.com/6735650/99185669-adfcfa00-274b-11eb-82d9-d584b7242e34.png)

Log:

![grafik](https://user-images.githubusercontent.com/6735650/99185630-69715e80-274b-11eb-9340-4c5328214b94.png)

```
                            Process ch.blinkenlights.android.vanilla created fo
                            r pre-top-activity {ch.blinkenlights.android.vanilla
                            /ch.blinkenlights.android.vanilla.LibraryActivity}
                            PID: 1460   UID:    GIDs: 

                 Zygote  I  seccomp disabled by setenforce 0
         android.vanill  E  Not starting debugger since process cannot load the 
                            jdwp agent.
     ApplicationLoaders  D  Returning zygote-cached class loader: /system/framew
                            ork/android.test.base.jar
  NetworkSecurityConfig  D  No Network Security Config specified, using platform
                             default
                         D  No Network Security Config specified, using platform
                             default
           VanillaMusic  W  Failed to load state
                         W  java.io.FileNotFoundException: /data/user/0/ch.blink
                            enlights.android.vanilla/files/state: open failed: E
                            NOENT (No such file or directory)
                         W      at libcore.io.IoBridge.open(IoBridge.java:492)
                         W      at java.io.FileInputStream.<init>(FileInputStrea
                            m.java:160)
                         W      at android.app.ContextImpl.openFileInput(Context
                            Impl.java:636)
                         W      at android.content.ContextWrapper.openFileInput(
                            ContextWrapper.java:216)
                         W      at ch.blinkenlights.android.vanilla.PlaybackServ
                            ice.loadState(PlaybackService.java:2040)
                         W      at ch.blinkenlights.android.vanilla.PlaybackServ
                            ice.onCreate(PlaybackService.java:450)
                         W      at android.app.ActivityThread.handleCreateServic
                            e(ActivityThread.java:4192)
                         W      at android.app.ActivityThread.access$1500(Activi
                            tyThread.java:237)
                         W      at android.app.ActivityThread$H.handleMessage(Ac
                            tivityThread.java:1932)
                         W      at android.os.Handler.dispatchMessage(Handler.ja
                            va:106)
                         W      at android.os.Looper.loop(Looper.java:223)
                         W      at android.app.ActivityThread.main(ActivityThrea
                            d.java:7656)
                         W      at java.lang.reflect.Method.invoke(Native Method
                            )
                         W      at com.android.internal.os.RuntimeInit$MethodAnd
                            ArgsCaller.run(RuntimeInit.java:592)
                         W      at com.android.internal.os.ZygoteInit.main(Zygot
                            eInit.java:947)
                         W  Caused by: android.system.ErrnoException: open faile
                            d: ENOENT (No such file or directory)
                         W      at libcore.io.Linux.open(Native Method)
                         W      at libcore.io.ForwardingOs.open(ForwardingOs.jav
                            a:166)
                         W      at libcore.io.BlockGuardOs.open(BlockGuardOs.jav
                            a:254)
                         W      at libcore.io.ForwardingOs.open(ForwardingOs.jav
                            a:166)
                         W      at android.app.ActivityThread$AndroidOs.open(Act
                            ivityThread.java:7542)
                         W      at libcore.io.IoBridge.open(IoBridge.java:478)
                         W      ... 14 more
            MediaPlayer  W  Use of stream types is deprecated for operations oth
                            er than volume control
                         W  See the documentation of setAudioStreamType() for wh
                            at to use instead with android.media.AudioAttributes
                             to qualify your playback use case
                         W  Use of stream types is deprecated for operations oth
                            er than volume control
                         W  See the documentation of setAudioStreamType() for wh
                            at to use instead with android.media.AudioAttributes
                             to qualify your playback use case
                   View  W  requestLayout() improperly called by android.widget.
                            LinearLayout{a714464 V.E...... ......ID 0,0-1080,154
                            } during layout: running second layout pass
                         W  requestLayout() improperly called by android.widget.
                            LinearLayout{e68c6cd V.E...... ......ID 0,154-1080,2
                            42} during layout: running second layout pass
                         W  requestLayout() improperly called by android.widget.
                            LinearLayout{ebd4b82 V.E...... ......ID 0,242-1080,3
                            96} during layout: running second layout pass
                         W  requestLayout() improperly called by com.mobeta.andr
                            oid.dslv.DragSortListView{c26f293 V.ED.VCL. ......ID
                             0,396-1080,2168 #7f0900a8 app:id/queue} during layo
                            ut: running second layout pass
           VanillaMusic  W  Returning default media-library preferences due to e
                            rror: java.io.FileNotFoundException: /data/user/0/ch
                            .blinkenlights.android.vanilla/files/_prefs-v1.obj: 
                            open failed: ENOENT (No such file or directory)
             AdrenoGLES  I  PFP: 0x016ee187, ME: 0x00000000
            ContextImpl  W  Failed to ensure /dev/null/Android/media/ch.blinkenl
                            ights.android.vanilla: java.lang.SecurityException: 
                            Invalid mkdirs path: /dev/null/Android/media/ch.blin
                            kenlights.android.vanilla is not a known app path.
         AndroidRuntime  E  FATAL EXCEPTION: MediaScannerThread
                         E  Process: ch.blinkenlights.android.vanilla, PID: 1460
                         E  java.lang.NullPointerException: Attempt to invoke vi
                            rtual method 'java.lang.String java.io.File.getAbsol
                            utePath()' on a null object reference
                         E      at ch.blinkenlights.android.medialibrary.MediaLi
                            brary.discoverDefaultMediaPaths(MediaLibrary.java:17
                            0)
                         E      at ch.blinkenlights.android.medialibrary.MediaLi
                            brary.getPreferences(MediaLibrary.java:149)
                         E      at ch.blinkenlights.android.medialibrary.MediaSc
                            anner.guessQuickScanPlan(MediaScanner.java:337)
                         E      at ch.blinkenlights.android.medialibrary.MediaSc
                            anner.handleMessage(MediaScanner.java:233)
                         E      at android.os.Handler.dispatchMessage(Handler.ja
                            va:102)
                         E      at android.os.Looper.loop(Looper.java:223)
                         E      at android.os.HandlerThread.run(HandlerThread.ja
                            va:67)
               Gralloc4  I  mapper 4.x is not supported
               Gralloc3  W  mapper 3.x is not supported
```

**Comment by adrian-bl** [comment]
This works for me on the Emulator and LineageOS 18.1 - could you try the latest nightly build (upgraded to SDK30) to see if the issue persists?

(See https://github.com/vanilla-music/vanilla#nightly-builds)

**Comment by gsantner** [comment]
@adrian-bl 
No issue is still present, tired the apk linked in readme.  
Notice: I don't have issues with other mediaplayers or music players, so should be a bug on vanilla.

![grafik](https://user-images.githubusercontent.com/6735650/107160009-d6d00c80-6993-11eb-934a-ae0611087960.png)

**Comment by gsantner** [comment]
@adrian-bl   
I downloaded the latest nightly. Immediatly crashes at startup still.

**Comment by petitminion** [comment]
I have a similar issue. Not sure it's the same.
Android 11 Xiaomi redmi 9t.
Application crash at startup with this log :

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
	at c.a.a.a.b.g(Unknown Source:32)
	at c.a.a.a.b.j(Unknown Source:86)
	at c.a.a.a.f.d(Unknown Source:2)
	at c.a.a.a.f.handleMessage(Unknown Source:134)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:226)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by gsantner** [comment]
Vanilla doesn't crash anymore. Thanks for the fix 👍
