### ISSUE TITLE
App crashes on resuming

### ISSUE THREAD

**Issue by opusforlife2** [vanilla-music/vanilla#1086]
- Vanilla Music Version (Settings -> About): 1.1.0
- Android Version: LOS 17.1
- Phone vendor / model: Xiaomi Mi 5
- Application was downloaded from (use `[x]`):
  - [x] F-Droid
- Did this work in a previous version?
  - [x] NA / Don't know.

## Steps to reproduce the issue

Play some music in Vanilla. Then pause it/let it be paused by another media app. Do something else for a while. Come back to Vanilla. Crash.

This behavious is not consistent, though. Sometimes it crashes, but other times it resumes just fine. Probably, a longer period away from the app would make it more likely to encounter a crash.

## Logs

```
FATAL EXCEPTION: main
Process: ch.blinkenlights.android.vanilla, PID: 5232
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=ch.blinkenlights.android.vanilla/.PlaybackService }: app is in background uid UidRecord{2ffc8d1 u0a175 LAST bg:+6m21s338ms idle change:cached procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1616)
	at android.app.ContextImpl.startService(ContextImpl.java:1571)
	at android.content.ContextWrapper.startService(ContextWrapper.java:669)
	at ch.blinkenlights.android.vanilla.r.onStart(Unknown Source:20)
	at ch.blinkenlights.android.vanilla.FullPlaybackActivity.onStart(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
	at android.app.Activity.performStart(Activity.java:7847)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by adrian-bl** [comment]
Interesting: Since Android 8.0, apps are only allowed to create services while the app is in foreground (or: create a foreground service (-> notification)): https://developer.android.com/about/versions/oreo/background

It's pretty strange that this happens while `FullPlaybackActivity.onStart()` is called since the app *is about to come* into the foreground.

Did you have this issue since forever or did it only start recently?

**Comment by opusforlife2** [comment]
I think it might have started in this or the previous version. I'm not sure, sorry.

**Comment by adrian-bl** [comment]
I tried to reproduce this today on an Android 10 device, but was unable to:

I tried to:

* Launch vanilla, play some song
* Hit pause over the notification
* Execute `am stopservice ch.blinkenlights.android.vanilla/.PlaybackService`via ADB which would kill the playback service immediately (and be restarted next time the app is launched)
* Re-launch vanilla

-> No crash, tried about 20 times :-/

How consistent can you reproduce the issue? Maybe we could catch the exception and fire off a worker thread which would try to create the activity once the app is fully launched.

**Comment by opusforlife2** [comment]
It's not consistent, as I've said. I've speculated on what might trigger it, but I can't reproduce it at will.

I can install a debug APK to test solutions out, if you want.

**Comment by opusforlife2** [comment]
Got the crash again. One line is slightly different this time:
```
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=ch.blinkenlights.android.vanilla/.PlaybackService }: app is in background uid UidRecord{a02f111 u0a175 CAC  bg:+12m39s511ms idle change:cached procs:1 seq(0,0,0)}
```

**Comment by opusforlife2** [comment]
This time I encountered the crash when my car Bluetooth connected and the phone tried to resume playing audio in Vanilla (since it was the last used media app). The error message was the same, so I didn't bother keeping the crash log.

**Comment by opusforlife2** [comment]
Got a pretty quick crash this time. The time between going away from Vanilla and coming back must have been less than a minute.

- Phone connected to car bluetooth. Song playing.
- Made a phone call. Song paused automatically.
- After call finished, song didn't resume automatically.
- Opened Vanilla.
- Crash.

It's the same crash as all the ones above.
