### ISSUE TITLE
DSP Manager crash

### ISSUE THREAD

**Issue by Scayris** [vanilla-music/vanilla#111]
As I wrote on Play Store comment, DSP manager force closes when a new song starts playing, every once in a while at first, then just continuously on every new song. Don't know where the bug lies, but it doesn't seem to happen with other players. Here's what I gathered from logcat:

```java
10-29 19:15:48.660 I/HeadsetService(20521): New audio session: 655
10-29 19:15:48.660 W/EffectsFactory(326): EffectCreate() library bundle: could not create fx Volume, error -22
10-29 19:15:48.660 E/AudioEffect(20521): set(): AudioFlinger could not create effect, status: -22
10-29 19:15:48.660 E/AudioEffects-JNI(20521): AudioEffect initCheck failed -4
10-29 19:15:48.660 E/AudioEffect-JAVA(20521): Error code -4 when initializing AudioEffect.
10-29 19:15:48.660 D/AndroidRuntime(20521): Shutting down VM
10-29 19:15:48.660 W/dalvikvm(20521): threadid=1: thread exiting with uncaught exception (group=0x41d30ce0)
10-29 19:15:48.660 E/AndroidRuntime(20521): FATAL EXCEPTION: main
10-29 19:15:48.660 E/AndroidRuntime(20521): Process: com.bel.android.dspmanager, PID: 20521
10-29 19:15:48.660 E/AndroidRuntime(20521): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.media.action.OPEN_AUDIO_EFFECT_CONTROL_SESSION flg=0x10 (has extras) } in com.bel.android.dspmanager.service.HeadsetService$1@42255718
10-29 19:15:48.660 E/AndroidRuntime(20521): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:776)
10-29 19:15:48.660 E/AndroidRuntime(20521): 	at android.os.Handler.handleCallback(Handler.java:733)
10-29 19:15:48.660 E/AndroidRuntime(20521): 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-29 19:15:48.660 E/AndroidRuntime(20521): 	at android.os.Looper.loop(Looper.java:136)
10-29 19:15:48.660 E/AndroidRuntime(20521): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
10-29 19:15:48.660 E/AndroidRuntime(20521): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-29 19:15:48.660 E/AndroidRuntime(20521): 	at java.lang.reflect.Method.invoke(Method.java:515)
10-29 19:15:48.660 E/AndroidRuntime(20521): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
10-29 19:15:48.660 E/AndroidRuntime(20521): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
10-29 19:15:48.660 E/AndroidRuntime(20521): 	at dalvik.system.NativeStart.main(Native Method)
10-29 19:15:48.660 E/AndroidRuntime(20521): Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Effect type: 09e8ede0-ddde-11db-b4f6-0002a5d5c51b not supported.
10-29 19:15:48.660 E/AndroidRuntime(20521): 	at com.bel.android.dspmanager.service.HeadsetService$EffectSet.<init>(HeadsetService.java:60)
10-29 19:15:48.660 E/AndroidRuntime(20521): 	at com.bel.android.dspmanager.service.HeadsetService$1.onReceive(HeadsetService.java:114)
10-29 19:15:48.660 E/AndroidRuntime(20521): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:766)
10-29 19:15:48.660 E/AndroidRuntime(20521): 	... 9 more
10-29 19:15:48.660 E/AndroidRuntime(20521): Caused by: java.lang.IllegalArgumentException: Effect type: 09e8ede0-ddde-11db-b4f6-0002a5d5c51b not supported.
10-29 19:15:48.660 E/AndroidRuntime(20521): 	at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:405)
10-29 19:15:48.660 E/AndroidRuntime(20521): 	at com.bel.android.dspmanager.service.HeadsetService$EffectSet.<init>(HeadsetService.java:57)
10-29 19:15:48.660 E/AndroidRuntime(20521): 	... 11 more
```

**Comment by adrian-bl** [comment]
Looks like we are leaking audioeffect sessions.
I'm going to subclass MediaPlayer to have it close the session on release().
This will also be a good opportunity to clean up the replayGain + gapless code

**Comment by aminb** [comment]
:+1:

**Comment by adrian-bl** [comment]
Fixed via: https://github.com/vanilla-music/vanilla/commit/4783d842b76f48dcaaf33285358cd73930139c5a
