### ISSUE TITLE
Crash in DSLV

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#202]
Reported via play store: (4 out of 5 crashes on Galaxy S6)

```
java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.MotionEvent.getX()' on a null object reference
at com.mobeta.android.dslv.DragSortController.onScroll(DragSortController.java:381)
at android.view.GestureDetector.onTouchEvent(GestureDetector.java:588)
at com.mobeta.android.dslv.DragSortController.onTouch(DragSortController.java:239)
at android.view.View.dispatchTouchEvent(View.java:9023)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2701)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2413)
at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:5305)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2712)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2428)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2712)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2428)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2712)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2428)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2679)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1797)
at android.app.Activity.dispatchTouchEvent(Activity.java:2878)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2640)
at android.view.View.dispatchPointerEvent(View.java:9234)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4781)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4619)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4170)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4223)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4189)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4299)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4197)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4356)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4170)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4223)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4189)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4197)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4170)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6648)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6532)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6503)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6738)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6709)
at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6761)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
at android.view.Choreographer.doCallbacks(Choreographer.java:590)
at android.view.Choreographer.doFrame(Choreographer.java:558)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6141)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by adrian-bl** [comment]
Also see: https://github.com/vanilla-music/vanilla/commit/7835436a3553f36e6457f8900ac9a5763b2bfbec

**Comment by xbao** [comment]
Ooo fun. My understanding of the crash log is as follows:

1. `DragSortController` receives touch events
2. It first delegates these to `GestureDetector#onTouch` 
3. `GestureDetector#onTouch` calls `DragSortController#onScroll`
4. The `ACTION_DOWN` event parameter is null -> crash

`GestureDetector` isn't receiving the `ACTION_DOWN` event before receiving the `ACTION_MOVE` event that triggers the controller's `onScroll`

7835436 made sure that ALL touch events the controller gets are delegated to the `GestureDetector`, in the hopes that the `ACTION_DOWN` event was just being eaten by that `if(...) return;` at the start of `onTouchEvent`

From a [0-point SO answer](http://stackoverflow.com/a/27925888/2631829) about onFling:
> If your touch place is outside view you will get null on e1. 

Could this be a cause? Starting the drag outside the `DragSortController`'s touch area and moving into it?

Do you have the versions of the devices affected? We have a couple of S6's at work, if I get a chance I'll try it out

**Comment by adrian-bl** [comment]
> Do you have the versions of the devices affected? We have a couple of S6's at work, if I get a chance I'll try it out

No, and neither me nor Amin were able to reproduce the crash on any other device.

It would be great if you could reproduce it on a S6.

But if we can not reproduce it, i'd suggest to revert 7835436 and check if e1 || e2 is null in onScroll: Ignoring a scroll event is still better than crashing ;-)

**Comment by xbao** [comment]
I got my hands on an S6 edge, our S6 is unavailable at the moment. I installed 1.0.31 from the play store. 

I tried tapping around like a maniac inside a playlist in edit mode and in the playing queue. Seemed fine.

Then I ran a monkey with 

```
adb shell monkey -p ch.blinkenlights.android.vanilla --pct-motion 100 --pct-majornav 0 --pct-touch 0 --pct-nav 0 --pct-trackball 0 --pct-syskeys 0 --pct-appswitch 0 --pct-anyevent 0 10000
```

It's crashing! But not with the DSLV issue :( stack traces. Which kind of makes sense because I can't get the damn thing to stay on the screen with the DSLV. Anyway, unrelated stack traces:

```
// CRASH: ch.blinkenlights.android.vanilla (pid 14405)
// Short Msg: java.lang.ArrayIndexOutOfBoundsException
// Long Msg: java.lang.ArrayIndexOutOfBoundsException: length=0; index=6
// Build Label: samsung/zeroltezt/zeroltechn:5.1.1/LMY47X/G9250ZTU1BOGB:user/release-keys
// Build Changelist: G9250ZTU1BOGB
// Build Time: 1437699022000
// java.lang.ArrayIndexOutOfBoundsException: length=0; index=6
// 	at ch.blinkenlights.android.vanilla.FileSystemAdapter.createData(FileSystemAdapter.java:291)
// 	at ch.blinkenlights.android.vanilla.FileSystemAdapter.onClick(FileSystemAdapter.java:313)
// 	at android.view.View.performClick(View.java:5254)
// 	at android.view.View$PerformClick.run(View.java:21179)
// 	at android.os.Handler.handleCallback(Handler.java:739)
// 	at android.os.Handler.dispatchMessage(Handler.java:95)
// 	at android.os.Looper.loop(Looper.java:145)
// 	at android.app.ActivityThread.main(ActivityThread.java:6837)
// 	at java.lang.reflect.Method.invoke(Native Method)
// 	at java.lang.reflect.Method.invoke(Method.java:372)
// 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
// 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

```
// CRASH: ch.blinkenlights.android.vanilla (pid 10774)
// Short Msg: java.lang.IllegalArgumentException
// Long Msg: java.lang.IllegalArgumentException: width and height must be > 0
// Build Label: samsung/zeroltezt/zeroltechn:5.1.1/LMY47X/G9250ZTU1BOGB:user/release-keys
// Build Changelist: G9250ZTU1BOGB
// Build Time: 1437699022000
// java.lang.IllegalArgumentException: width and height must be > 0
// 	at android.graphics.Bitmap.createBitmap(Bitmap.java:934)
// 	at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
// 	at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
// 	at ch.blinkenlights.android.vanilla.CoverBitmap.generateDefaultCover(CoverBitmap.java:348)
// 	at ch.blinkenlights.android.vanilla.CoverView.generateBitmap(CoverView.java:370)
// 	at ch.blinkenlights.android.vanilla.CoverView.handleMessage(CoverView.java:462)
// 	at android.os.Handler.dispatchMessage(Handler.java:98)
// 	at android.os.Looper.loop(Looper.java:145)
// 	at android.os.HandlerThread.run(HandlerThread.java:61)
//
```

I'm tracking down the S6, I'll give that a go another morning

**Comment by xbao** [comment]
Another one:

```
// CRASH: ch.blinkenlights.android.vanilla (pid 19937)
// Short Msg: android.database.CursorIndexOutOfBoundsException
// Long Msg: android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 0
// Build Label: samsung/zeroltezt/zeroltechn:5.1.1/LMY47X/G9250ZTU1BOGB:user/release-keys
// Build Changelist: G9250ZTU1BOGB
// Build Time: 1437699022000
// android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 0
// 	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
// 	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
// 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
// 	at android.database.CursorWrapper.getString(CursorWrapper.java:114)
// 	at ch.blinkenlights.android.vanilla.MediaAdapter.buildLimiter(MediaAdapter.java:418)
// 	at ch.blinkenlights.android.vanilla.LibraryActivity.expand(LibraryActivity.java:449)
// 	at ch.blinkenlights.android.vanilla.LibraryActivity.onItemExpanded(LibraryActivity.java:503)
// 	at ch.blinkenlights.android.vanilla.MediaAdapter.onClick(MediaAdapter.java:585)
// 	at android.view.View.performClick(View.java:5254)
// 	at android.view.View$PerformClick.run(View.java:21179)
// 	at android.os.Handler.handleCallback(Handler.java:739)
// 	at android.os.Handler.dispatchMessage(Handler.java:95)
// 	at android.os.Looper.loop(Looper.java:145)
// 	at android.app.ActivityThread.main(ActivityThread.java:6837)
// 	at java.lang.reflect.Method.invoke(Native Method)
// 	at java.lang.reflect.Method.invoke(Method.java:372)
// 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
// 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
//
```

**Comment by adrian-bl** [comment]
Oh, nice.

I can reproduce the FilesystemAdapter crash on my device: Looks like the monkey test manages to click on an element while clear() has been called. I'll have a look at this.

The MediaAdapter crash is probably a similar race condition.
..but the bitmap-crash confuses me ;-)

**Comment by xbao** [comment]
Nice. Yeah, the bitmap one is strange. I think the offending line might be CoverView.generateBitmap(CoverView.java:370):

```
mDefaultCover = CoverBitmap.generateDefaultCover(context, getWidth(), getHeight());
```

I'm guessing the view isn't laid out when this is called, so width and height are both zero which propagates through to the exception.

Looks like our non-edge S6 is being monopolised by a project. I'll take a look when I get a chance but I'm not sure when that will be, probably best to use that onScroll check.

**Comment by adrian-bl** [comment]
closing this - never saw it again in the playstore report
