### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by y7575355** [vanilla-music/vanilla#248]
java.lang.OutOfMemoryError
    at android.graphics.Bitmap.nativeCreate(Native Method)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:708)
    at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:595)
    at ch.blinkenlights.android.vanilla.CoverBitmap.createScaledBitmap(CoverBitmap.java:333)
    at ch.blinkenlights.android.vanilla.CoverBitmap.createBitmap(CoverBitmap.java:136)
    at ch.blinkenlights.android.vanilla.CoverView.generateBitmap(CoverView.java:375)
    at ch.blinkenlights.android.vanilla.CoverView.handleMessage(CoverView.java:462)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:136)
    at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by adrian-bl** [comment]
What kind of device are you using?
Also: does this happen always/often or only using a specific image?

**Comment by y7575355** [comment]
Oneplus one

**Comment by y7575355** [comment]
In the latest ver no pics appear

**Comment by adrian-bl** [comment]
There are multiple 'latest' versions: 1.0.33 is the latest in the play store, 1.0.34 is the latest available from f-droid - what version are you running?

So the code crashes while loading the source bitmap: do you have some (unusually large) album cover on your phone?

**Comment by y7575355** [comment]
1.033 fdroid
Maybe i have big pics but when i used to run earlier version it showed me pics and did not crash
I'm sorry i'm not sure when it began to crash i think 0.99 was better in crash wise

**Comment by y7575355** [comment]
The crash log was taken from cracker the xposed part 
Can i help or send something else?

**Comment by adrian-bl** [comment]
Crashing in this place is quite unusual as it only tries to assemble already scaled pictures.

Did you customize the DPI settings of your phone?
And: did you try to reboot the phone? Getting killed via Out of Memory doesn't necessarily mean that Vanilla is at fault - some other app / process could have slowly started to eat up all memory.

You could also give this version a try:
https://mega.nz/#!bgN33IgT!PMkjEcB_MNZlKUVJEaxiYS5J-4tL38KbciHoev69pQs
(You must uninstall any other installed versions before installing thisone as it is signed with a different key)
It will still crash but will log the dimensions of the to-be-scaled bitmap before calling createScaledBitmap() (Search for 'VanillaMusic' in the logcat)

**Comment by y7575355** [comment]
No for dpi Dont know.how
Reboot every week.or so doesnt effect vanilla crashes
Somehow i cant donwnload from mega.nz
Can u upload to.different server?

**Comment by xbao** [comment]
Attached (need to remove `.txt` extension): [VanillaMusic-debug.apk.txt](https://github.com/vanilla-music/vanilla/files/40677/VanillaMusic-debug.apk.txt). Also uploaded here: https://owncloud.xbc.nz/index.php/s/5bHXoTQpKYr8KXI

**Comment by y7575355** [comment]
Thank yousomething else

**Comment by y7575355** [comment]
java.lang.IllegalStateException
    at android.media.MediaPlayer.prepare(Native Method)
    at ch.blinkenlights.android.vanilla.PlaybackService.prepareMediaPlayer(PlaybackService.java:627)
    at ch.blinkenlights.android.vanilla.PlaybackService.triggerGaplessUpdate(PlaybackService.java:748)
    at ch.blinkenlights.android.vanilla.PlaybackService.handleMessage(PlaybackService.java:1539)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:136)
    at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by y7575355** [comment]
Is it better debug?

**Comment by y7575355** [comment]
11-23 00:33:06.353 E/AndroidRuntime(22698): 	at ch.blinkenlights.android.vanilla.PlaybackService.triggerGaplessUpdate(PlaybackService.java:748)

**Comment by y7575355** [comment]
Device Name: A0001
Android Version: 4.4.4
Screen class: normal
Density class: xxhdpi
Total Width (px): 1080
Total Height (px): 1920
App-usable Width (px): 1080
App-usable Height (px): 1920
Width (dp): 360
Height (dp): 640
Smallest DP: 360
Long or Wide: Yes
Natural Orientation: Portrait
Current Orientation: 0
Touchscreen: Finger
Screen DPI: 480
X DPI: 403.411
Y DPI: 403.041
Logical Density: 3.0
Font Scale Density: 3.0
Calculated Diagonal (inches): 5.5
Calculated Diagonal (mm): 139.0
Pixel Format: Not Available
Refresh Rate (fps): 63.0

Report prepared by ScreenInfo. Get yourself a copy: https://play.google.com/store/apps/details?id=com.jotabout.screeninfo

**Comment by adrian-bl** [comment]
sorry for the long delay: i just returned a few days ago from holidays.

> java.lang.IllegalStateException at android.media.MediaPlayer.prepare(Native Method)

That's a different error and not related to the out of memory crash (probably)

Did you try to install the version at https://owncloud.xbc.nz/index.php/s/5bHXoTQpKYr8KXI/download ?

**Comment by adrian-bl** [comment]
closing due to lack of reply
