### ISSUE TITLE
crash in settings->library screen->filebrowser home

### ISSUE THREAD

**Issue by zldrq** [vanilla-music/vanilla#251]
i just press it and get message "unfortunately vanill musec has stopped"
is there some log or smth i can give you?

**Comment by adrian-bl** [comment]
Yes: i would need the output of logcat.

Eg: run 'adb logcat' and post the last ~50 lines after the crash happened.

What Version of Android are you running?

**Comment by zldrq** [comment]
i think that is:


```I/ActivityManager(  720): Displayed ch.blinkenlights.android.songpocketswitcher/.PreferencesActivity: +333ms

I/Keyboard.Facilitator(12089): onFinishInput()

I/BatteryStatsImpl(  720): Stop partial wakelock ActivityManager-Launch(uid=1000, pid=720) nesting 2

D/WifiStateMachine(  720): ConnectedState{ what=131155 when=-3ms arg1=154 }

D/WifiStateMachine(  720): L2ConnectedState{ what=131155 when=-3ms arg1=154 }

D/wpa_supplicant(21101): wpa_s 0x40c0aed0 cmd SIGNAL_POLL

D/wpa_supplicant(21101): nl80211: survey data missing!

I/ActivityManager(  720): START {act=android.intent.action.MAIN cmp=ch.blinkenlights.android.songpocketswitcher/.PreferencesActivity (has extras) u=0} from pid 10331

I/BatteryStatsImpl(  720): Start partial wakelock ActivityManager-Launch(uid=1000, pid=720) nesting 3

W/Resources(10331): Converting to string: TypedValue{t=0x10/d=0x7 a=-1}

W/Resources(10331): Converting to string: TypedValue{t=0x10/d=0x3 a=-1}

V/PhoneStatusBar( 1380): setLightsOn(true)

I/ActivityManager(  720): Displayed ch.blinkenlights.android.songpocketswitcher/.PreferencesActivity: +353ms

I/Keyboard.Facilitator(12089): onFinishInput()

I/BatteryStatsImpl(  720): Stop partial wakelock ActivityManager-Launch(uid=1000, pid=720) nesting 2

I/Kate.LongPoll(19919): code=200

D/WifiStateMachine(  720): ConnectedState{ what=131155 when=-3ms arg1=154 }

D/WifiStateMachine(  720): L2ConnectedState{ what=131155 when=-5ms arg1=154 }

D/wpa_supplicant(21101): wpa_s 0x40c0aed0 cmd SIGNAL_POLL

D/wpa_supplicant(21101): nl80211: survey data missing!

W/dalvikvm(10331): threadid=1: thread exiting with uncaught exception (group=0x41ba1498)

I/ActivityManager(  720): START {cmp=ch.blinkenlights.android.vanilla/.FilebrowserStartActivity u=0} from pid 10331

E/AndroidRuntime(10331): FATAL EXCEPTION: main

E/AndroidRuntime(10331): android.content.ActivityNotFoundException: Unable to find explicit activity class {ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.FilebrowserStartActivity}; have you declared this activity in your AndroidManifest.xml?

E/AndroidRuntime(10331): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java)

E/AndroidRuntime(10331): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java)

E/AndroidRuntime(10331): 	at android.app.Activity.startActivityForResult(Activity.java)

E/AndroidRuntime(10331): 	at android.app.Activity.startActivityForResult(Activity.java)

E/AndroidRuntime(10331): 	at android.app.Activity.startActivity(Activity.java)

E/AndroidRuntime(10331): 	at android.app.Activity.startActivity(Activity.java)

E/AndroidRuntime(10331): 	at android.preference.Preference.performClick(Preference.java)

E/AndroidRuntime(10331): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java)

E/AndroidRuntime(10331): 	at android.widget.AdapterView.performItemClick(AdapterView.java)

E/AndroidRuntime(10331): 	at android.widget.AbsListView.performItemClick(AbsListView.java)

E/AndroidRuntime(10331): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java)

E/AndroidRuntime(10331): 	at android.widget.AbsListView$1.run(AbsListView.java)

E/AndroidRuntime(10331): 	at android.os.Handler.handleCallback(Handler.java)

E/AndroidRuntime(10331): 	at android.os.Handler.dispatchMessage(Handler.java)

E/AndroidRuntime(10331): 	at android.os.Looper.loop(Looper.java)

E/AndroidRuntime(10331): 	at android.app.ActivityThread.main(ActivityThread.java)

E/AndroidRuntime(10331): 	at java.lang.reflect.Method.invokeNative(Native Method)

E/AndroidRuntime(10331): 	at java.lang.reflect.Method.invoke(Method.java)

E/AndroidRuntime(10331): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)

E/AndroidRuntime(10331): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

E/AndroidRuntime(10331): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)

E/AndroidRuntime(10331): 	at dalvik.system.NativeStart.main(Native Method)

I/Whetstone_KLO( 2140): [am_crash][1449133357]:[10331,ch.blinkenlights.android.songpocketswitcher,1208532548,android.content.ActivityNotFoundException,Unable to find explicit activity class {ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.FilebrowserStartActivity}; have you declared this activity in your AndroidManifest.xml?,Instrumentation.java,-1]

W/ActivityManager(  720):   Force finishing activity ch.blinkenlights.android.songpocketswitcher/.PreferencesActivity
```

**Comment by adrian-bl** [comment]
Thanks for the log: you seem to use some fork of vanilla music: the app you are using identifies itself as  ch.blinkenlights.android.songpocketswitcher in the crash.

But my app is ch.blinkenlights.android (how 'nice' that the fork keeps using my domain in the package name)

So there is nothing i can do about the crash as you are using a different player.

**Comment by okungnyo** [comment]
From a one-second Google search, maybe some Russian copycat who's selling your app in some regional app store?
