### ISSUE TITLE
Crash on Android 4.2

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#267]
java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:695)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:674)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:607)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:487)
	at ch.blinkenlights.android.vanilla.CoverBitmap.createScaledBitmap(CoverBitmap.java:333)
	at ch.blinkenlights.android.vanilla.CoverBitmap.createBitmap(CoverBitmap.java:136)
	at ch.blinkenlights.android.vanilla.CoverView.generateBitmap(CoverView.java:375)
	at ch.blinkenlights.android.vanilla.CoverView.handleMessage(CoverView.java:462)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:194)
	at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by xbao** [comment]
Very similar to the crash I found on the S6 while investigating the DSLV issue: https://github.com/vanilla-music/vanilla/issues/202#issuecomment-140229467

**Comment by xbao** [comment]
Interesting, the MSG_GENERATE_BITMAP message is only sent when width and height are > 0: 2149745f52f14a0c53bcaede590217de376e1295. Race condition perhaps?

**Comment by adrian-bl** [comment]
hopefully fixed by https://github.com/vanilla-music/vanilla/commit/a347f38eb70bd57bdf31bd24bff3395e7e8407a4
