### ISSUE TITLE
crash on 4.x and 5.x

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#268]
java.lang.IllegalStateException
    at android.media.MediaPlayer.setNextMediaPlayer(Native Method)
    at ch.blinkenlights.android.vanilla.VanillaMediaPlayer.setNextMediaPlayer(VanillaMediaPlayer.java:91)
    at ch.blinkenlights.android.vanilla.PlaybackService.triggerGaplessUpdate(PlaybackService.java:754)
    at ch.blinkenlights.android.vanilla.PlaybackService.handleMessage(PlaybackService.java:1539)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:135)
    at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by xbao** [comment]
I did a bit of spelunking. The native `setNextMediaPlayer` is defined at [android_media_MediaPlayer.cpp#777](http://androidxref.com/4.4.2_r1/xref/frameworks/base/media/jni/android_media_MediaPlayer.cpp#777)

It throws a few `IllegalStateException`s but they all have messages, so it's more likely the exception was thrown by `process_media_player_call` (called by the native `setNextMediaPlayer`)  at [android_media_MediaPlayer.cpp#166](http://androidxref.com/4.4.2_r1/xref/frameworks/base/media/jni/android_media_MediaPlayer.cpp#166)

Any ideas on the cause or how to reproduce?

**Comment by adrian-bl** [comment]
Thanks for looking into this: i do not have a way to reproduce this bug and it seems to happen rarely.
Maybe we are just the victim of a broken gapless implementation :-/

I'll try to catch a few more crashes (so far there were only two reports) to narrow down the affected class of devices.
