### ISSUE TITLE
Crash in ICS remote

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#275]
**java.lang.NullPointerException
	at ch.blinkenlights.android.vanilla.RemoteControlImplICS.updateRemote(RemoteControlImplICS.java:141)
	at ch.blinkenlights.android.vanilla.PlaybackService.broadcastChange(PlaybackService.java:1065)
	at ch.blinkenlights.android.vanilla.PlaybackService.handleMessage(PlaybackService.java:1533)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:136)
	at android.os.HandlerThread.run(HandlerThread.java:61)**

**Comment by adrian-bl** [comment]
*may* be fixed via https://github.com/vanilla-music/vanilla/commit/924a8189de15fc6662397eb2c62bb0a033efe518 (but will probably cause new crashes....)
