### ISSUE TITLE
Crash on Android 4.1.2

### ISSUE THREAD

**Issue by folol** [vanilla-music/vanilla#276]
When ever i click on the expand button in Genre fragment , application is crashing 
![screenshot 1](https://cloud.githubusercontent.com/assets/8148617/12774870/f9c70c3a-ca6e-11e5-99fe-1162d9e3cb9d.png)

**Comment by adrian-bl** [comment]
This works fine for me in the emulator running 4.1.2

Does this happen on a real device?
Could you get a full logcat? Android is actually supposed to print out the faulty SQL query to the adb log

**Comment by folol** [comment]
Yes , It's happening on my device - HTC desire 700
In second screenshot faulty query is shown by cursor .
![screenshot 2](https://cloud.githubusercontent.com/assets/8148617/12806158/7947eba4-cb29-11e5-8d18-ecaf5696e3e1.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/8148617/12806162/7da68926-cb29-11e5-9d88-56d678ab24b5.png)

**Comment by adrian-bl** [comment]
This still doesn't show the faulty query: Please get a *FULL LOGCAT* (via adb logcat, not filtered by android studio) or add:
Log.v("VanillaMusic", selection);
to queryResolver() to catch it.

**Comment by xbao** [comment]
Got a similar crash on nightly. Got it while a song was playing in the background and I was searching through the 'Songs' tab. Tried to reproduce but I couldn't. Device is a Sony Xperia Z3+ running 5.0.1

Build info:

```
name='ch.blinkenlights.android.vanillanightly' 
versionCode='1454436674'
versionName='1.0.36' 
platformBuildVersionName='6.0-2438415'
```

Stacktrace:

```
02-05 10:35:57.900 16560 16560 E AndroidRuntime: FATAL EXCEPTION: main
02-05 10:35:57.900 16560 16560 E AndroidRuntime: Process: ch.blinkenlights.android.vanillanightly, PID: 16560
02-05 10:35:57.900 16560 16560 E AndroidRuntime: android.database.CursorIndexOutOfBoundsException: Index 1 requested, with a size of 1
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:74)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.database.CursorWrapper.getLong(CursorWrapper.java:106)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at ch.blinkenlights.android.vanillanightly.MediaAdapter.getItemId(MediaAdapter.java:623)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.widget.AbsListView.setSelectionFromTop(AbsListView.java:6848)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.widget.ListView.setSelection(ListView.java:1988)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at ch.blinkenlights.android.vanillanightly.LibraryPagerAdapter.handleMessage(LibraryPagerAdapter.java:658)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:211)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5335)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

Logcat:

```
02-03 12:08:31.106 21399 21399 E AndroidRuntime: Process: ch.blinkenlights.android.vanilla, PID: 21399
02-03 12:08:31.106 21399 21399 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application android.app.Application: java.lang.IllegalStateException: Unable to get package info for ch.blinkenlights.android.vanilla; is package not installed?
02-03 12:08:31.106 21399 21399 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Unable to get package info for ch.blinkenlights.android.vanilla; is package not installed?
02-05 10:34:21.890  1233  1254 I MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@1c108f61ch.blinkenlights.android.vanillanightly.PlaybackService@ad6e533
02-05 10:34:22.089 16560 16560 E MediaPlayer: Should have subtitle controller already set
02-05 10:34:22.089 16560 16586 E MediaPlayer: Should have subtitle controller already set
02-05 10:34:22.164 16560 16585 V RenderScript: Application requested CPU execution
02-05 10:34:22.199 16560 16585 V RenderScript: 0x7f9a171000 Launching thread(s), CPUs 8
02-05 10:34:23.118 16560 16560 I Timeline: Timeline: Activity_launch_request id:ch.blinkenlights.android.vanillanightly time:144788110
02-05 10:34:23.490  1233  1299 I ActivityManager: Displayed ch.blinkenlights.android.vanillanightly/.FullPlaybackActivity: +360ms
02-05 10:34:23.503 16560 16585 D OpenGLRenderer: endAllStagingAnimators on 0x7f97d93000 (RippleDrawable) with handle 0x7f9a1b3ae0
02-05 10:34:23.514 16560 16560 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@ac6363e time:144788506
02-05 10:34:23.693  1233  1299 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{fa388c u0 ch.blinkenlights.android.vanillanightly/.FullPlaybackActivity t3811} time:144788686
02-05 10:34:41.786 16560 20084 W MediaPlayer: info/warning (2, 0)
02-05 10:34:41.911 16560 16560 E MediaPlayer: Should have subtitle controller already set
02-05 10:34:41.911 16560 16586 E MediaPlayer: Should have subtitle controller already set
02-05 10:34:44.495 16560 16586 V VanillaMusic: performGC: items removed=0
02-05 10:35:21.941  1735  1735 W PackageManager: Failure retrieving resources for ch.blinkenlights.android.vanillanightly: Resource ID #0x0
02-05 10:35:43.466  1233  1299 I ActivityManager: Displayed ch.blinkenlights.android.vanillanightly/.LibraryActivity: +176ms
02-05 10:35:43.466  1233  1299 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{2f6ce4a2 u0 ch.blinkenlights.android.vanillanightly/.LibraryActivity t3822} time:144868458
02-05 10:35:43.523 16560 16560 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@c93e3a1 time:144868516
02-05 10:35:45.002 16560 16560 I Timeline: Timeline: Activity_launch_request id:ch.blinkenlights.android.vanillanightly time:144869994
02-05 10:35:45.175 16560 16560 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@eaa384e time:144870167
02-05 10:35:45.181  1233  1299 I ActivityManager: Displayed ch.blinkenlights.android.vanillanightly/.FullPlaybackActivity: +171ms
02-05 10:35:45.183 16560 16585 D OpenGLRenderer: endAllStagingAnimators on 0x7f9c462800 (RippleDrawable) with handle 0x7f9a1b3920
02-05 10:35:45.426  1233  1299 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{2e9a136f u0 ch.blinkenlights.android.vanillanightly/.FullPlaybackActivity t3822} time:144870418
02-05 10:35:51.842 16560 16560 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
02-05 10:35:51.844 16560 16560 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
02-05 10:35:54.199 16560 16560 I Timeline: Timeline: Activity_launch_request id:ch.blinkenlights.android.vanillanightly time:144879191
02-05 10:35:54.347 16560 16585 D OpenGLRenderer: endAllStagingAnimators on 0x7f97004000 (RippleDrawable) with handle 0x7f97da75a0
02-05 10:35:54.357 16560 16560 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@c93e3a1 time:144879350
02-05 10:35:54.488  1233  1299 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{2f6ce4a2 u0 ch.blinkenlights.android.vanillanightly/.LibraryActivity t3822} time:144879480
02-05 10:35:57.900 16560 16560 D AndroidRuntime: Shutting down VM
02-05 10:35:57.900 16560 16560 E AndroidRuntime: FATAL EXCEPTION: main
02-05 10:35:57.900 16560 16560 E AndroidRuntime: Process: ch.blinkenlights.android.vanillanightly, PID: 16560
02-05 10:35:57.900 16560 16560 E AndroidRuntime: android.database.CursorIndexOutOfBoundsException: Index 1 requested, with a size of 1
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:74)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.database.CursorWrapper.getLong(CursorWrapper.java:106)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at ch.blinkenlights.android.vanillanightly.MediaAdapter.getItemId(MediaAdapter.java:623)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.widget.AbsListView.setSelectionFromTop(AbsListView.java:6848)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.widget.ListView.setSelection(ListView.java:1988)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at ch.blinkenlights.android.vanillanightly.LibraryPagerAdapter.handleMessage(LibraryPagerAdapter.java:658)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:211)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5335)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
02-05 10:35:57.900 16560 16560 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
02-05 10:35:57.933   586   586 I JavaDumper: JavaDumperThread: addEvent: data_app_crash@1454628957932.txt processName: ch.blinkenlights.android.vanillanightly
02-05 10:37:49.585 16560 16560 I Process : Sending signal. PID: 16560 SIG: 9
02-05 10:37:49.720 11964 11964 D AudioManager: updateMediaPlayerList: Remove RCC ch.blinkenlights.android.vanillanightly from List
02-05 10:37:49.721 17469 11937 W AudioFlinger: session id 97 not found for pid 16560
02-05 10:37:49.803  1233  2202 V AudioService: Player entry for ch.blinkenlights.android.vanilla is not present
02-05 10:37:49.803  1233  2202 E AudioService: Removing Player: ch.blinkenlights.android.vanillanightly from index2
02-05 10:37:52.010  2366  2366 I Timeline: Timeline: Activity_launch_request id:ch.blinkenlights.android.vanillanightly time:144997002
02-05 10:37:52.317 11964 11964 V RemoteController: Updating current controller package as ch.blinkenlights.android.vanillanightly from null
02-05 10:37:52.323 11964 11964 D AudioManager: updateMediaPlayerList: Add RCC ch.blinkenlights.android.vanillanightly to List
02-05 10:37:52.325  1233  2316 E AudioService: Player: ch.blinkenlights.android.vanillaLost Focus
02-05 10:37:52.325  1233  2316 E AudioService: Adding Player: ch.blinkenlights.android.vanillanightly to available player list
02-05 10:37:52.326  1233  2316 V AudioService: updating focussed RCC change to RCD: CallingPackageName:ch.blinkenlights.android.vanillanightly
02-05 10:37:52.463  1233  1299 I ActivityManager: Displayed ch.blinkenlights.android.vanillanightly/.LibraryActivity: +441ms
02-05 10:37:52.464  1233  1299 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{1b710521 u0 ch.blinkenlights.android.vanillanightly/.LibraryActivity t3823} time:144997456
02-05 10:37:53.792 13711 13711 I Timeline: Timeline: Activity_launch_request id:ch.blinkenlights.android.vanillanightly time:144998784
02-05 10:37:53.998  1233  1299 I ActivityManager: Displayed ch.blinkenlights.android.vanillanightly/.FullPlaybackActivity: +183ms
02-05 10:37:54.207  1233  1299 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{c303aef u0 ch.blinkenlights.android.vanillanightly/.FullPlaybackActivity t3823} time:144999199
02-05 10:37:55.198  1233  1299 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{1b710521 u0 ch.blinkenlights.android.vanillanightly/.LibraryActivity t3823} time:145000191
02-05 10:38:03.971 13711 13711 I Timeline: Timeline: Activity_launch_request id:ch.blinkenlights.android.vanillanightly time:145008964
02-05 10:38:04.165  1233  1299 I ActivityManager: Displayed ch.blinkenlights.android.vanillanightly/.FullPlaybackActivity: +180ms
02-05 10:38:04.366  1233  1299 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{7644a3a u0 ch.blinkenlights.android.vanillanightly/.FullPlaybackActivity t3823} time:145009358
02-05 10:38:04.771  1233  1832 I MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@3f438410ch.blinkenlights.android.vanillanightly.PlaybackService@3bfb4fec
02-05 10:38:08.514  1233  1299 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{1b710521 u0 ch.blinkenlights.android.vanillanightly/.LibraryActivity t3823} time:145013506
02-05 10:38:44.272 13711 13711 I Timeline: Timeline: Activity_launch_request id:ch.blinkenlights.android.vanillanightly time:145049265
02-05 10:38:44.485  1233  1299 I ActivityManager: Displayed ch.blinkenlights.android.vanillanightly/.FullPlaybackActivity: +199ms
02-05 10:38:44.693  1233  1299 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{152f5813 u0 ch.blinkenlights.android.vanillanightly/.FullPlaybackActivity t3823} time:145049685
02-05 10:38:48.246  1233  1299 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{1b710521 u0 ch.blinkenlights.android.vanillanightly/.LibraryActivity t3823} time:145053239
02-05 10:42:25.444 13711 13737 V VanillaMusic: performGC: items removed=0
```

**Comment by adrian-bl** [comment]
@xbao That seems to be a different issue, i opened #282 for this.

After quickly looking at it, the following seems to happen:

In LibraryPagerAdapter:
Something runs MSG_RUN_QUERY which calls MSG_COMMIT_QUERY.

The code then tries to get the cached position of this adapter+limiter combination:
```
		case MSG_COMMIT_QUERY: {
			int pos = 0;
			int index = message.arg1;
			mAdapters[index].commitQuery(message.obj);

			Limiter curLimiter = mAdapters[index].getLimiter();
			Integer curPos = sLruAdapterPos.getPosition(mAdapters[index]);
			if (curPos != null)
				pos = (int)curPos;

			mLists[index].setSelection(pos);
			break;
		}
```

The position might be outdated due to various reasons (eg: search or adding and deleting files)
The code then calls setSelection which does not really check the value of `pos'.
Later then, the adapter code calls MediaAdapter:getItemId() of an invalid position, causing a crash.

**Comment by folol** [comment]
@adrian-bl 
Well, I added the Log.v("VanillaMusic",selection) to queryResolver() and it is showing that selection is actually empty . 
![screenshot 5](https://cloud.githubusercontent.com/assets/8148617/12886268/054027d2-ce92-11e5-9d60-ad451e22a23a.png)

**Comment by adrian-bl** [comment]
Oh, my bad: I we are doing some very hacky stuff in the genre limiter and (if i remember correctly) the actual sql query should be in selectionArgs[0]

**Comment by adrian-bl** [comment]
closing due to lack of response
