### ISSUE TITLE
Crash when viewing the queue

### ISSUE THREAD

**Issue by mathstuf** [vanilla-music/vanilla#329]
New in 1.0.38 (pretty sure; definitely worked within the past month though). Have 2300 songs in the queue. I'll try and get a backtrace when back at a PC (Monday).

**Comment by adrian-bl** [comment]
Did you get a chance to capture a trace of the crash?

When did it actually crash: while expanding the queue display or while 'using' it?

**Comment by mathstuf** [comment]
Thanks for the reminder. Only having one A <-> C cable makes connecting harder now that logcat apps don't work :( .

```adb
04-24 12:03:02.185 17158 17158 E AndroidRuntime: FATAL EXCEPTION: main
04-24 12:03:02.185 17158 17158 E AndroidRuntime: Process: ch.blinkenlights.android.vanilla, PID: 17158
04-24 12:03:02.185 17158 17158 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at java.util.ArrayList.get(ArrayList.java:310)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at ch.blinkenlights.android.vanilla.SlidingView.setExpansionStage(SlidingView.java:157)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at ch.blinkenlights.android.vanilla.SlidingView.expandSlide(SlidingView.java:132)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at ch.blinkenlights.android.vanilla.PlaybackActivity.onOptionsItemSelected(PlaybackActivity.java:411)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at ch.blinkenlights.android.vanilla.FullPlaybackActivity.onOptionsItemSelected(FullPlaybackActivity.java:425)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at android.app.Activity.onMenuItemSelected(Activity.java:2914)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1151)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:200)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at android.widget.AdapterView.performItemClick(AdapterView.java:310)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at android.widget.AbsListView$3.run(AbsListView.java:3903)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5422)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-24 12:03:02.185 17158 17158 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-24 12:03:02.208   879   890 W ActivityManager:   Force finishing activity ch.blinkenlights.android.vanilla/.FullPlaybackActivity
```

**Comment by adrian-bl** [comment]
Hmm: That's an odd crash: It seems like onLayout() never got called, so parts of the View are not initialized :-/

Does this happen always? What version (+ device) of Android are you using?

**Comment by mathstuf** [comment]
Always happens. Nexus 5x with 1.0.38 from F-Droid with Android 6.0.1.

**Comment by adrian-bl** [comment]
Strange: I just tested it on my Nexus 5 (non-x) with 6.0.1 and it works fine - Android N in the Emulator also doesn't have any issues :-/

Could you please give this test build a try and send me the output of 'adb logcat | grep Vanilla' after launching the app? http://neo01.eqmx.net/android/vanilla-measure-log.apk

**Comment by mathstuf** [comment]
Hrm, It won't install; likely due to a signing key mismatch. Is it possible to rename the APK path for a side-by-side install?

**Comment by mathstuf** [comment]
Oh, playlists are saved between installs (well, at least Apollo can see the same playlists as vanilla). Installing that APK.

**Comment by adrian-bl** [comment]
Yes: Playlists are system-wide & public, you'll only lose your playcounts counter.

If it still helps: this version uses a different package name: http://neo01.eqmx.net/android/vanilla-measure-log2.apk

**Comment by mathstuf** [comment]
Well, that one doesn't crash in the queue display.

```adb
04-24 14:51:12.391 20566 20566 W VanillaMusic: Failed to load state
04-24 14:51:12.391 20566 20566 W VanillaMusic: java.io.FileNotFoundException: /data/user/0/ch.blinkenlights.android.vanilla/files/state: open failed: ENOENT (No such file or directory)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at libcore.io.IoBridge.open(IoBridge.java:452)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at java.io.FileInputStream.<init>(FileInputStream.java:76)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at android.app.ContextImpl.openFileInput(ContextImpl.java:384)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at android.content.ContextWrapper.openFileInput(ContextWrapper.java:177)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at ch.blinkenlights.android.vanilla.PlaybackService.loadState(PlaybackService.java:1940)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at ch.blinkenlights.android.vanilla.PlaybackService.onCreate(PlaybackService.java:440)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at android.app.ActivityThread.-wrap4(ActivityThread.java)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at android.os.Handler.dispatchMessage(Handler.java:102)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at android.os.Looper.loop(Looper.java:148)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at android.app.ActivityThread.main(ActivityThread.java:5422)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at java.lang.reflect.Method.invoke(Native Method)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-24 14:51:12.391 20566 20566 W VanillaMusic: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at libcore.io.Posix.open(Native Method)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  at libcore.io.IoBridge.open(IoBridge.java:438)
04-24 14:51:12.391 20566 20566 W VanillaMusic:  ... 14 more
04-24 14:51:12.429 20566 20566 V VanillaMusic: onWindowVisibilityChanged
04-24 14:51:12.455 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:12.477 20566 20589 I Adreno  : QUALCOMM build                   : 63c06b2, I8366cd0437
04-24 14:51:12.477 20566 20589 I Adreno  : Build Date                       : 12/06/15
04-24 14:51:12.477 20566 20589 I Adreno  : OpenGL ES Shader Compiler Version: XE031.05.13.02
04-24 14:51:12.477 20566 20589 I Adreno  : Local Branch                     : mybranch17112971
04-24 14:51:12.477 20566 20589 I Adreno  : Remote Branch                    : quic/LA.BF64.1.2.9_v2
04-24 14:51:12.477 20566 20589 I Adreno  : Remote Branch                    : NONE
04-24 14:51:12.477 20566 20589 I Adreno  : Reconstruct Branch               : NOTHING
04-24 14:51:12.483 20566 20589 I OpenGLRenderer: Initialized EGL, version 1.4
04-24 14:51:12.500 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:12.503 20566 20566 V VanillaMusic: onLayout
04-24 14:51:12.504 20566 20566 W View    : requestLayout() improperly called by android.widget.LinearLayout{162576 V.E...... ......ID 0,0-1794,147} during layout: running second layout pass
04-24 14:51:12.504 20566 20566 W View    : requestLayout() improperly called by android.widget.LinearLayout{81c1777 V.E...... ......ID 0,147-1794,220} during layout: running second layout pass
04-24 14:51:12.504 20566 20566 W View    : requestLayout() improperly called by android.widget.LinearLayout{266fe4 V.E...... ......ID 0,220-1794,346} during layout: running second layout pass
04-24 14:51:12.505 20566 20566 W View    : requestLayout() improperly called by com.mobeta.android.dslv.DragSortListView{4cd4c4d V.ED.VCL. ......ID 0,346-1794,1017 #7f0c0027 app:id/queue} during layout: running second layout pass
04-24 14:51:12.505 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:12.507 20566 20566 V VanillaMusic: onLayout
04-24 14:51:12.510 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:12.512 20566 20566 V VanillaMusic: onLayout
04-24 14:51:12.513 20566 20566 V VanillaMusic: setSlaveViewStage
04-24 14:51:12.513 20566 20566 V VanillaMusic: setSlaveViewStage
04-24 14:51:12.513 20566 20566 W View    : requestLayout() improperly called by android.widget.LinearLayout{e9dcf81 V.E...... ......ID 0,0-1794,1017 #7f0c0031 app:id/content} during layout: running second layout pass
04-24 14:51:12.557   879   897 V WindowManager: Layouts looping: On entry to LockedInner, mPendingLayoutChanges = 0x1
04-24 14:51:12.558   879   897 V WindowManager: Layouts looping: after finishPostLayoutPolicyLw, mPendingLayoutChanges = 0x0
04-24 14:51:12.559   879   897 V WindowManager: Layouts looping: mLayoutNeeded, mPendingLayoutChanges = 0x1
04-24 14:51:12.560   879   897 V WindowManager: Layouts looping: On entry to LockedInner, mPendingLayoutChanges = 0x1
04-24 14:51:12.561   879   897 V WindowManager: Layouts looping: after finishPostLayoutPolicyLw, mPendingLayoutChanges = 0x0
04-24 14:51:12.562   879   897 V WindowManager: Layouts looping: mLayoutNeeded, mPendingLayoutChanges = 0x1
04-24 14:51:12.563   879   897 E WindowManager: Performed 6 layouts in a row. Skipping
04-24 14:51:12.566 29756 29756 I Keyboard.Facilitator: onFinishInput()
04-24 14:51:12.569 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:12.572   879   897 I ActivityManager: Displayed ch.blinkenlights.android.vanilla/.LibraryActivity: +397ms
04-24 14:51:12.579 20566 20566 V VanillaMusic: onLayout
04-24 14:51:12.593 20566 20566 V VanillaMusic: setSlaveViewStage
04-24 14:51:12.719   879   897 I WindowManager: Screen frozen for +510ms due to Window{f28412f u0 NavigationBar}
04-24 14:51:13.392   879  2653 D WifiStateMachine: starting scan for "boeckel-tibbits"WPA_PSK with 2462,5180
04-24 14:51:14.730   879   897 I art     : Starting a blocking GC Explicit
04-24 14:51:14.911   879   897 I art     : Explicit concurrent mark sweep GC freed 30066(2MB) AllocSpace objects, 24(756KB) LOS objects, 30% free, 36MB/52MB, paused 1.258ms total 178.275ms
04-24 14:51:20.963 10125 10152 D tgnet   : time for push ping
04-24 14:51:20.965 10125 10152 D tgnet   : connection(0xebc72f00, dc1, type 8) send message (session: 0x9ca64bf49f6b6858, seqno: 0, messageid: 0x571d15a8f70a3c00): 24TL_ping_delay_disconnect(0xdc6462a0)
04-24 14:51:20.967 10125 10152 D tgnet   : dc1 send ping to push connection
04-24 14:51:20.969 10125 10152 D tgnet   : schedule next epoll wakeup in 29995 ms
04-24 14:51:20.970 10125 10152 D tgnet   : setting network alarm to wake us in 29995 ms
04-24 14:51:20.980 10125 10152 D tgnet   : schedule next epoll wakeup in 29983 ms
04-24 14:51:20.980 10125 10152 D tgnet   : setting network alarm to wake us in 29983 ms
04-24 14:51:20.990 10125 10152 D tgnet   : schedule next epoll wakeup in 29973 ms
04-24 14:51:20.991 10125 10152 D tgnet   : setting network alarm to wake us in 29973 ms
04-24 14:51:21.037 10125 10152 D tgnet   : schedule next epoll wakeup in 29926 ms
04-24 14:51:21.038 10125 10152 D tgnet   : setting network alarm to wake us in 29926 ms
04-24 14:51:21.046 10125 10152 E tgnet   : connection(0xebc72f00, dc1, type 8) received message len 88 equal to packet size
04-24 14:51:21.046 10125 10152 D tgnet   : connection(0xebc72f00, dc1, type 8) received object 7TL_pong
04-24 14:51:21.047 10125 10152 D tgnet   : connection(0xebc72f00, dc1, type 8) received push ping
04-24 14:51:21.047 10125 10152 D tgnet   : schedule next epoll wakeup in 179916 ms
04-24 14:51:21.048 10125 10152 D tgnet   : setting network alarm to wake us in 179916 ms
04-24 14:51:42.493   879  3313 I ActivityManager: START u0 {cmp=ch.blinkenlights.android.vanilla/.FullPlaybackActivity} from uid 10193 on display 0
04-24 14:51:42.586 20566 20566 V VanillaMusic: SlidingView created
04-24 14:51:42.589 20566 20566 V VanillaMusic: onFinishInflate
04-24 14:51:42.602 20566 20566 V VanillaMusic: onWindowVisibilityChanged
04-24 14:51:42.606 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:42.632 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:42.633 20566 20566 V VanillaMusic: onLayout
04-24 14:51:42.634 20566 20566 W View    : requestLayout() improperly called by android.widget.LinearLayout{12b1b5e V.E...... ......ID 0,0-1794,126 #7f0c0026 app:id/queue_slider} during layout: running second layout pass
04-24 14:51:42.634 20566 20566 W View    : requestLayout() improperly called by com.mobeta.android.dslv.DragSortListView{a657b3f V.ED.VCL. ......ID 0,126-1794,660 #7f0c0027 app:id/queue} during layout: running second layout pass
04-24 14:51:42.634 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:42.636 20566 20566 V VanillaMusic: onLayout
04-24 14:51:42.647 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:42.647 20566 20566 V VanillaMusic: onLayout
04-24 14:51:42.712   879   897 I ActivityManager: Displayed ch.blinkenlights.android.vanilla/.FullPlaybackActivity: +173ms
04-24 14:51:42.712 29756 29756 I Keyboard.Facilitator: onFinishInput()
04-24 14:51:42.713 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:42.714 20566 20566 V VanillaMusic: onLayout
04-24 14:51:42.724 20566 20566 V VanillaMusic: onWindowVisibilityChanged
04-24 14:51:44.340 20566 20566 V VanillaMusic: onWindowVisibilityChanged
04-24 14:51:44.341 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:44.361 20566 20566 V VanillaMusic: onLayout
04-24 14:51:44.389 29756 29756 I Keyboard.Facilitator: onFinishInput()
04-24 14:51:44.404 20566 20566 V VanillaMusic: onWindowVisibilityChanged
04-24 14:51:44.421   372   372 W SurfaceFlinger: couldn't log to binary event log: overflow.
04-24 14:51:45.118   879 26034 W BackupManagerService: dataChanged but no participant pkg='ch.blinkenlights.android.vanilla' uid=10193
04-24 14:51:45.139 29756 29756 I Keyboard.Facilitator: onFinishInput()
04-24 14:51:47.043   879  3381 W BackupManagerService: dataChanged but no participant pkg='ch.blinkenlights.android.vanilla' uid=10193
04-24 14:51:47.673 29756 29756 I Keyboard.Facilitator: onFinishInput()
04-24 14:51:47.749   879 25281 W BackupManagerService: dataChanged but no participant pkg='ch.blinkenlights.android.vanilla' uid=10193
04-24 14:51:47.913   487  2637 E MetadataRetrieverClient: failed to extract an album art
04-24 14:51:48.537   879 25320 I ActivityManager: START u0 {cmp=ch.blinkenlights.android.vanilla/.PlaylistActivity (has extras)} from uid 10193 on display 0
04-24 14:51:48.677   879   897 I ActivityManager: Displayed ch.blinkenlights.android.vanilla/.PlaylistActivity: +115ms
04-24 14:51:48.678 29756 29756 I Keyboard.Facilitator: onFinishInput()
04-24 14:51:48.749 20566 20566 V VanillaMusic: onWindowVisibilityChanged
04-24 14:51:50.260 20566 20566 V VanillaMusic: onWindowVisibilityChanged
04-24 14:51:50.262 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:50.280 20566 20566 V VanillaMusic: onLayout
04-24 14:51:50.303 29756 29756 I Keyboard.Facilitator: onFinishInput()
04-24 14:51:52.525   879  5459 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@c64c502 attribute=null, token = android.os.BinderProxy@a1dc8c0
04-24 14:51:52.557   372   372 W SurfaceFlinger: couldn't log to binary event log: overflow.
04-24 14:51:52.598 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:52.654 20566 20566 V VanillaMusic: onLayout
04-24 14:51:52.659 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:52.659 20566 20566 V VanillaMusic: onLayout
04-24 14:51:52.669 20566 20574 W CursorWrapperInner: Cursor finalized without prior close()
04-24 14:51:52.761   487 20687 D NuPlayerDriver: notifyListener_l(0xf2e34b40), (1, 0, 0)
04-24 14:51:52.763 20566 20590 D MediaPlayer: setSubtitleAnchor in MediaPlayer
04-24 14:51:52.806   487 27294 D NuPlayerDriver: start(0xf2e34b40), state is 4, eos is 0
04-24 14:51:52.807   487 20687 I GenericSource: start
04-24 14:51:52.857 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:52.858 20566 20566 V VanillaMusic: onLayout
04-24 14:51:52.861 20313 20313 V MusicFXControlPanelReceiver: onReceive
04-24 14:51:52.862 20313 20313 V MusicFXControlPanelReceiver: Action: android.media.action.OPEN_AUDIO_EFFECT_CONTROL_SESSION
04-24 14:51:52.864 20313 20313 V MusicFXControlPanelReceiver: Package name: ch.blinkenlights.android.vanilla
04-24 14:51:52.866 20313 20313 V MusicFXControlPanelReceiver: Audio session: 6390
04-24 14:51:52.868  1026  1041 I art     : Background partial concurrent mark sweep GC freed 2096(92KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 11MB/18MB, paused 4.885ms total 170.091ms
04-24 14:51:52.888 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:52.889 20566 20566 V VanillaMusic: onLayout
04-24 14:51:52.899   879  3352 I MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@8562761ch.blinkenlights.android.vanilla.PlaybackService@e472033 req=1flags=0x0
04-24 14:51:52.905 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:52.906 20566 20566 V VanillaMusic: onLayout
04-24 14:51:52.923 20313 20313 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@a712119, ch.blinkenlights.android.vanilla, 6390)
04-24 14:51:52.929   487 20692 E OMXNodeInstance: setConfig(6c1:google.vorbis.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
04-24 14:51:52.929   487 20692 I ACodec  : codec does not support config priority (err -2147483648)
04-24 14:51:52.931   487 20692 I MediaCodec: MediaCodec will operate in async mode
04-24 14:51:52.948   487  2629 D audio_hw_primary: out_set_parameters: enter: usecase(0: deep-buffer-playback) kvpairs: routing=2
04-24 14:51:52.951   487 20687 D NuPlayerDriver: notifyListener_l(0xf2e34b40), (6, 0, 0)
04-24 14:51:52.974   487  2629 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
04-24 14:51:52.974   487  2629 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(101)
04-24 14:51:52.975   487  2629 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 1
04-24 14:51:52.980   487  2629 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(71) acdb_id(102)
04-24 14:51:52.980   487  2629 D audio_hw_primary: enable_snd_device: snd_device(71: vi-feedback)
04-24 14:51:52.981   487  2629 D audio_hw_primary: enable_audio_route: apply and update mixer path: spkr-vi-record
04-24 14:51:52.998   487 20698 D NuPlayerDriver: notifyListener_l(0xf1ba2b00), (1, 0, 0)
04-24 14:51:52.999 20566 20590 D MediaPlayer: setSubtitleAnchor in MediaPlayer
04-24 14:51:52.999 20566 20566 D MediaPlayer: setSubtitleAnchor in MediaPlayer
04-24 14:51:53.006   487  2629 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(28) acdb_id(4)
04-24 14:51:53.007   487  2629 I ACDB-LOADER: ACDB AFE returned = -19
04-24 14:51:53.007   487  2629 D audio_hw_primary: enable_audio_route: apply and update mixer path: deep-buffer-playback
04-24 14:51:53.089 20566 20589 V RenderScript: 0x7f92fa8000 Launching thread(s), CPUs 6
04-24 14:51:53.136   487  2629 D AudioFlinger: mixer(0xf39c0000) throttle end: throttle time(54)
04-24 14:51:53.382   879  2653 E native  : do suspend false
04-24 14:51:53.625   879 25320 I ActivityManager: START u0 {cmp=ch.blinkenlights.android.vanilla/.FullPlaybackActivity} from uid 10193 on display 0
04-24 14:51:53.676 20566 20566 V VanillaMusic: SlidingView created
04-24 14:51:53.688 20566 20566 V VanillaMusic: onFinishInflate
04-24 14:51:53.704 20566 20566 V VanillaMusic: onWindowVisibilityChanged
04-24 14:51:53.706 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:53.729 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:53.773 20566 20566 V VanillaMusic: onLayout
04-24 14:51:53.775 20566 20566 W View    : requestLayout() improperly called by android.widget.LinearLayout{30c7a3 V.E...... ......ID 0,0-1794,126 #7f0c0026 app:id/queue_slider} during layout: running second layout pass
04-24 14:51:53.775 20566 20566 W View    : requestLayout() improperly called by com.mobeta.android.dslv.DragSortListView{caadaa0 VFED.VCL. ......ID 0,126-1794,660 #7f0c0027 app:id/queue} during layout: running second layout pass
04-24 14:51:53.775 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:53.777 20566 20566 V VanillaMusic: onLayout
04-24 14:51:53.784 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:53.786 20566 20566 V VanillaMusic: onLayout
04-24 14:51:53.814   879   897 I ActivityManager: Displayed ch.blinkenlights.android.vanilla/.FullPlaybackActivity: +175ms
04-24 14:51:53.814 29756 29756 I Keyboard.Facilitator: onFinishInput()
04-24 14:51:53.817 20566 20566 V VanillaMusic: onMeasure
04-24 14:51:53.819 20566 20566 V VanillaMusic: onLayout
04-24 14:51:53.831 20566 20566 V VanillaMusic: onWindowVisibilityChanged
```

Only removed some bits related to ESSID scanning and DHCP renewal.

**Comment by mathstuf** [comment]
Huh. Installing the F-Droid version again and it doesn't crash now. Could something have been bad in the state file which was written?

**Comment by adrian-bl** [comment]
Hmm, that's very odd :-)

> Could something have been bad in the state file which was written?

No: The state file is only used to save the queue + position.
And a corrupted preferences database shouldn't cause such issues as the queue-view doesn't have any saved state

**Comment by adrian-bl** [comment]
I'm closing this issue as it seems to be a 'mysterious android bug':
Somewhat must have caused android to not call onLayout - while magically rendering the view: there is no way how this could happen under normal circumstances.

Feel free to re-open the bug if the crash happens again.
