### ISSUE TITLE
Random crashes while trying to show toast for new song

### ISSUE THREAD

**Issue by kirbyfan64** [vanilla-music/vanilla#677]
- Vanilla Music Version (Settings -> About): Nightly Thu Sep 21 20:30:20
- Android Version: 7.1
- Phone vendor / model: Nexus 5
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [ ] F-Droid
  - [x] Other (Nightly Build)
- Did this work in a previous version?
  - [x] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

You know that toast that appears when a new song starts playing? Well, Vanilla keeps randomly crashing with this logcat:

![logcat](https://s3.nofilecdn.io/g/SKx7imOYPungbIkX6PKuNYgpeCEW8gHCAgNtFfYy96BAhd39LYgnNoSeebEjXDlj/Screenshot_20170924-085107.png/p)

## Steps to reproduce the issue

No clue, but I've accidentally "reproduced" it three times in an hour...

## Screenshot / Video (If applicable)

~~use your imagination~~

**Comment by adrian-bl** [comment]
That's interesting: i've seen a couple of them in the play store console, but they all came from a 'Wilefox Switft' device running Android 7.1, while you got a Nexus (Do you run Lineage OS or the stock rom?)


I'm not sure how this happens: Which buttons are you pressing? or: which text would the notification have if it didn't crash?

**Comment by kirbyfan64** [comment]
I'm running a couple-month-old version of [this ROM](https://forum.xda-developers.com/google-nexus-5/development/rom-pure-nexus-substratum-t3477787). For me, the crashes always occur when I press a song title to play it, and I'm assuming the toast would have said *1 track playing*.

I'm not sure if that I hit home too quickly after switching songs? I mean, I think the crash has happened before without switching quickly, but I think it happens more frequently if I do? Maybe Android is killing the activity too quickly before the toast is shown?

**Comment by kirbyfan64** [comment]
Happened twice again: at this point I'm pretty sure it's only when I hit a song to play and almost immediately hit home afterwards.

**Comment by Adonai** [comment]
@kirbyfan64 , the crash you captured should be the close friend of another one, which contains real reason. When crash happens some views lose their parent activity and are closed this way. Are you sure there's nothing around these lines? This may not be Vanilla-related, stacktraces may be going to libhwc.so, libcore.so or libsurfaceflinger.so, so try not filtering by Vanilla.

**Comment by kirbyfan64** [comment]
Only other traceback I could find:

```
W/MessageQueue( 3186): Handler (loc) {ddaaeb3} sending message to a Handler on a dead thread
W/MessageQueue( 3186): java.lang.IllegalStateException: Handler (loc) {ddaaeb3} sending message to a Handler on a dead thread
W/MessageQueue( 3186): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
W/MessageQueue( 3186): 	at android.os.Handler.enqueueMessage(Handler.java:643)
W/MessageQueue( 3186): 	at android.os.Handler.sendMessageAtTime(Handler.java:612)
W/MessageQueue( 3186): 	at android.os.Handler.sendMessageDelayed(Handler.java:582)
W/MessageQueue( 3186): 	at android.os.Handler.sendMessage(Handler.java:519)
W/MessageQueue( 3186): 	at loc.a(:com.google.android.gms@11517438)
W/MessageQueue( 3186): 	at loa.c(:com.google.android.gms@11517438:10)
W/MessageQueue( 3186): 	at loa.a(:com.google.android.gms@11517438:25)
W/MessageQueue( 3186): 	at koo.a(:com.google.android.gms@11517438)
W/MessageQueue( 3186): 	at koy.onTransact(:com.google.android.gms@11517438:3)
W/MessageQueue( 3186): 	at android.os.Binder.execTransact(Binder.java:565)
```

It *is* worth noting that the logcat mentioned shortly before that my system was low on memory, which IIRC also had happened another time this crash occurred.

The traceback mentions that the activity could maybe not be running...could it be Android killing Vanilla's display activity, and then Vanilla can't recover?

**Comment by adrian-bl** [comment]
Well, the crash doesn't even happen in Vanilla itself: It's the WindowManager going bananas and throwing exceptions - Vanilla Music just shows up in the log because it triggered the toast message.

I'll try to play around with this in the emulator when i have time (eg: trigger toast and let PM kill the process). But i doubt that there is much we can do (apart from using the raw applicationContext - maybe?)

**Comment by kirbyfan64** [comment]
Would it at least be possible to avoid crashing all of Vanilla when the toast fails to show?

**Comment by adrian-bl** [comment]
The crash isn't happening in vanilla itself:

Android kills the process because it thinks it shouldn't exist anymore

**Comment by kirbyfan64** [comment]
Well, whenever this happens it always says *Vanilla music has crashed*...

**Comment by adrian-bl** [comment]
> Well, whenever this happens it always says Vanilla music has crashed...

I don't doubt that: what i wanted to say is that the exception doesn't happen in our process, so we can't catch it: We just told the OS to show a toast (which gets turned into a message inside androids framework) - at some point the OS says 'nope' and just kills the process which sent the message.

I tried to trigger this in the Emulator today but didn't have any success :-/
Will try with a real device running LOS14 next week.

**Comment by Adonai** [comment]
@adrian-bl , there's a setting "Don't keep activities" in developer settings, maybe that'll help.

**Comment by adrian-bl** [comment]
Sorry for my slowness, was quite busy in the last few weeks:

I still don't see how this crash happens, so i did the only sane thing and pushed some random code changes (9fa3b1b98c893fb8c472b0b70184a887d04b2036).

They are already included in the latest nightly build. Could you give it a try to see if the issue got better? (or worse?)

**Comment by kirbyfan64** [comment]
Just downloaded it. I'll run it for a few days and see if I can get it to crash...

**Comment by kirbyfan64** [comment]
Nvm it still crashes...I can actually pretty accurately reproduce it now that I've fiddled a bit. I basically play a new track, then hit the multitasking button and swipe to close the activity before it shows the toast. (Of course, when it crashes for me I just switch apps, and Android closes the activity, but it's harder to reproduce consistently that way...)

**Comment by adrian-bl** [comment]
> I basically play a new track, then hit the multitasking button and swipe to close the activity before it 
> shows the toast. 

Wow, you must be pretty fast! I have trouble showing the task list before the toast appears.

I tried again to reproduce this, but no matter what i try, it never happens on my phone:
I changed the code to add a 1 sec delay to toasts (so that i have a chance to get to the task list) and configured android to have no background processes.

I can see Vanilla getting killed sometimes (expected), but i never ever got one of these crashes :-/

**Comment by Adonai** [comment]
Maybe we can use application context for this?

**Comment by kirbyfan64** [comment]
Hmm...it seems kind of random again. I'm guessing this is one of those weird device-specific things...

Sorry...I swear the bugs I file here are the weirdest ones. :/

**Comment by adrian-bl** [comment]
@Adonai i already changed it to use getApplicationContext() :-/

@kirbyfan64 you are not the only user with this issue: i see the same crashes from a small number of devices in the play store developer console

**Comment by adrian-bl** [comment]
@kirbyfan64 i hacked up https://github.com/vanilla-music/vanilla/commit/cf62017e909aee518917369fce54334893a4d20e which dispatches the toast message to a (known, long lived) background thread. Could you please give it (again) a try?

...I start to run out of ideas :-/

**Comment by adrian-bl** [comment]
@kirbyfan64 ping: is the latest version less crashy for you?

**Comment by kirbyfan64** [comment]
Sorry, I'll try again on my (now "old") Nexus 5 later.

**Comment by adrian-bl** [comment]
Any news on this?
Looking at the play store, it seems that the crash rate decreased (but didn't drop to zero)
