### ISSUE TITLE
[Bug] Headphone detector for Vanilla Music doesn't detect headphones

### ISSUE THREAD

**Issue by Tianonymus** [vanilla-music/vanilla#955]
Hello, I tried out Headphone detector for Vanilla Music today after not having used it for some time. Unfortunately it does not work on my device since it updated to Android 8. 

Please see below for info. Thanks. 

- Vanilla Music Version: 1.0.83
- Headphone detector Version: 1.7
- Android Version: 8.1.0
- Phone vendor / model: LG K8 (2017)
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

Headphone detector for Vanilla Music (HdfVM) doesn't detect headphones when plugged in.

Installed the latest version, headphones weren't detected. Restarted device, a message is shown that HdfVM is closed (paraphrased, don't use English device: "Unfortunately HdfVM has been closed". Can't say if it's an Android message dialogue or belongs to the app). Headphones aren't detected when Vanilla Music has been started before plugging in either.

Below is a log of the crash.

If I remember correctly this is an issue since the phone updated to Android 8/8.1.

## Steps to reproduce the issue

Install HdfVM 
Restart device
Message is shown that HdfVM crashed 

## Log

[05-09 01:01:03.708 6220:6220 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: ch.blinkenlights.android.vanillaplug, PID: 6220
java.lang.RuntimeException: Unable to start receiver ch.blinkenlights.android.vanillaplug.BootReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=ch.blinkenlights.android.vanillaplug/.VPlugService }: app is in background uid UidRecord{c0a85de u0a425 RCVR idle change:uncached procs:1 seq(0,0,0)}
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3310)
	at android.app.ActivityThread.-wrap17(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:175)
	at android.app.ActivityThread.main(ActivityThread.java:6722)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=ch.blinkenlights.android.vanillaplug/.VPlugService }: app is in background uid UidRecord{c0a85de u0a425 RCVR idle change:uncached procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1522)
	at android.app.ContextImpl.startService(ContextImpl.java:1478)
	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
	at ch.blinkenlights.android.vanillaplug.BootReceiver.onReceive(BootReceiver.java:29)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3299)
	... 8 more

**Comment by wchen342** [comment]
I had the same problem too so I did some search. The problem is [background services are limited from Android O](https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten).
A quick fix is changing `startService` to `startForegroundService` which will eliminate the error, but the service will get killed after 5 seconds unless it displays a notification, which is not a good solution.

**Comment by adrian-bl** [comment]
Not sure if the headphone detector app will ever be useful on more recent android versions.

As wchen342 noted, you are required to show a permanent notification to not get killed.

> I think a better way is to move the function to the player and recieve system broadcast 
> there directly.

That wouldn't solve the issue: Vanilla also gets killed after ~5 sec of inactivity (= not playing a song, not showing a notification)

**Comment by wchen342** [comment]
I think there are three possible solutions:

1. Move this functionality to the player and only do headset detection when the player is running. This requires users to run the player once, and the player shall keep its notification alive even not playing unless the users manually quit it.

2. On device boot up, run the service which displays a notification shortly then deletes the notification.

3. Use a `JobIntentService` which pulls the headset status every second on Android 8+. Battery consumption can be a problem in this case.

I prefer solution 1 since starting playing music on boot up even the users never start the player is probably not so desirable, and the player's notification will keep the users aware that the music will possibly play when they plug their headset in.

**Comment by breversa** [comment]
https://github.com/marverenic/Jockey apparently has such a feature, but I have no idea how it's implemented.

**Comment by breversa** [comment]
This feature is SO useful when getting ready for a drive : I get in my car, plug the audio plug in the jack, and the music starts, without having to touch the screen. Simply awesome. :)

**Comment by breversa** [comment]
@adrian-bl :
Many background apps have now gone ahead with a permanent notification, and I use the OS's (LineageOs 16 at the moment) notification settings to hide the ones I don't care about. I for one wouldn't blame you about going this way too. :)

**Comment by breversa** [comment]
Any news on this issue ? It’s one of the features that I’m missing the most, and the most often (several times daily).

**Comment by wchen342** [comment]
@breversa I am no longer working on this project. You need to ask @adrian-bl whether he is gonna fix this or not.

**Comment by breversa** [comment]
Thank you @wchen342 for your reply.

For now, I've found a workaround user Easer (https://f-droid.org/packages/ryey.easer/) :
- Create a condition "headphone plugged in" (or whatever it's called in your language).
- Create a profile with "start application" = "ch.blinkenlights.android.vanilla", and "media control" = "play/pause" (strangely, "play" only doesn't seem to work as reliably).
- Create a script on the created condition, and add the created profile.

However, this solution is less than ideal :
- one more app to install.
- one more notification to clutter my notification drawer/area. I know that even Vanilla couldn't really go around this (when in "stand-by"), but it could at least be merged in the "Now playing" notification when, well, playing.
- it's not average user-friendly to set up.
- it puts Vanilla in the foreground, when one of my typical use case is "start my navigation app, plug car audio cable in, and drive". Sure it can then be put in the background, but even a tad bit of hassle is still a hassle.

However, the logic is there : a background task (with the mandatory notification that can be hidden by the OS (at least with LineageOS) that waits for the headphone to be plugged in, then merges with the "Now playing" notification.
@adrian-bl, what do you think about it ?

**Comment by wchen342** [comment]
@breversa That's an interesting approach.

One thing I noticed recently is that a lot of applications like `firefox` are now trying to show a notification at startup and make it hidden very shortly, which keep the application running without disturbing the user. I think that may be a solution.

**Comment by breversa** [comment]
> @adrian-bl :
> Many background apps have now gone ahead with a permanent notification, and I use the OS's (LineageOs 16 at the moment) notification settings to hide the ones I don't care about. I for one wouldn't blame you about going this way too. :)

Wait wait wait… I see here https://cdn.rawgit.com/vanilla-music/vanilla/HEAD/app/src/main/assets/about.html :

> 1.0.91
> - NEW Switch to new notification framework

Does that mean that Vanilla Music may have a permanent notification that would bring back the headphones detector back ? :D

**Comment by adrian-bl** [comment]
No: this just means that we are using the androidx/support APIs to build the notification.

To get the headphone detector app working on newer SDK versions, we would need to change the app (not vanilla) to display a permanent notification.

**Comment by breversa** [comment]
Alright, I understand.

Once again, I'm all for a permanent notification (I can use the OS to hide it) if that allows to solve this issue. :)

**Comment by matgoebl** [comment]
Another alternative is using A2DP Volume (https://github.com/jroal/a2dpvolume), that is also available via f-droid. It uses the permanent notification method    to survive in background.

**Comment by VA1DER** [comment]
Is there any movement on this?  Every other player I use can pause when I turn off my headset and resume when I turn it on.  It's really the only functionality I'm missing in VM.

**Comment by breversa** [comment]
My workaround was to switch to https://github.com/oxygencobalt/Auxio
